### ISSUE TITLE
kcl executable (and others) missing from github releases

### ISSUE THREAD

**Issue by starkers** [kcl-lang/kcl#1019]
## Bug Report

Github releases since `0.7.1` are missing the wrapper shell scripts (eg `bin/kcl`).

For example:

![image](https://github.com/kcl-lang/kcl/assets/462087/84686552-1d08-4927-a517-6edb2deb5b23)

Was this deliberate or is it a bug? This has luckily not broken the neovim integration (as the LSP server remains intact) however this has broken the `asdf` plugin for releases from `0.7.2` onwards

### 1. Minimal reproduce step (Required)

Decompress or view the GitHub release artifacts (only linux/amd64 tested)

### 2. What did you expect to see? (Required)

executables such as:
- `kclvm/bin/kcl`

### 3. What did you see instead (Required)

Many missing files

### 4. What is your KCL components version? (Required)

all releases `=>` 0.7.2

See latest release below 🤭

![image](https://github.com/kcl-lang/kcl/assets/462087/f25c6621-22cb-4c61-9858-bfec245203df)

**Comment by Peefy** [comment]
Sorry, I've added kcl executable into github releases since kcl v0.7.5 versions
