### ISSUE TITLE
[LFX PreTest] PreTest for LSP quick fix

### ISSUE THREAD

**Issue by He1pa** [kcl-lang/kcl#1020]
Provide quick fix with LSP for this case.
![image](https://github.com/kcl-lang/kcl/assets/56333845/d0ff6e7b-4148-4af8-9f5c-982d73b2ea89)

What you need to do:
1. Find the place where this error is generated in the kcl compiler(~/kclvm/sema/src/resolver/scope.rs  lookup_type_from_scope() and set_type_to_scope()) and fill in `suggested_replacement` in the structure representing the error. In this case it would be `Some("aaa")`
2. Convert KCL's Diagnostic to LSP's Diagnostic. Most of the work is already done, but you need to convert `suggested_replacement` into the `data` field.
```
pub struct Diagnostic {
    /// The range at which the message applies.
    pub range: Range,
   ...
    ///  A data entry field that is preserved between a `textDocument/publishDiagnostics`
    /// notification and `textDocument/codeAction` request.
    pub data: Option<serde_json::Value>,
}
```
3. handle the `CodeActionRequest` and provide a quick fix response. you can ref this pr: https://github.com/kcl-lang/kcl/pull/652. This is a very simple demo that fix warning about useless import. It replaces the useless import stmt with an empty string. But you need to get the `new_text` from RequestParam(The IDE will return the `data` generated in the previous step as a parameter)
4. Install KCL extension within VSCode and build lsp binary locally, add the `kcl-language-server` to PATH
5. After completing above, you can see a button like this in the IDE (VSCode). Click the button and the IDE will fix the incorrect code (aa->aaa)
![image](https://github.com/kcl-lang/kcl/assets/56333845/763aed1c-3f2f-4ac9-a315-6e46fef1c138)

You can fork this repository and develop in your own repository. After completion, you can contact me via email or slack. Of course, if you have any questions during this process, you can also contact me

**Comment by UtkarshUmre** [comment]
As there is a reference provided, I can seek help from that. Since this is a good first issue, I would like to give it a try

**Comment by He1pa** [comment]
> Do we need to create a gist for this or how do we present our solutions? cc @He1pa @Peefy

You can fork this repository and develop in your own repository. After completion, you can contact me via email or slack. Of course, if you have any questions during this process, you can also contact me

**Comment by Bhaskary20** [comment]
I would like to take this issue
