### ISSUE TITLE
Support path escape in override parameters of the KCL CLI

### ISSUE THREAD

**Issue by FLAGLORD** [kcl-lang/kcl#1022]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Assuming that a schema definition has an attribute `labels`(type is `str:str`) , I need to override a key including the dot( `.` )  e.g. `kcl.io/key1`. As the dot `.` is a reserved word of the `identifier` in [override_spec](https://kcl-lang.io/docs/user_docs/guides/automation/#2-use-kcl-cli-for-automation), we can't use `instance.labels.kcl.io/key1` to indicates the identifier that needs to modify the configuration.

**Describe the feature you'd like:**

Support path escape like `instance.labels.kcl\.io/key1`. The format `schema.labels["kcl.io/key1"]` is an alternative choice.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Peefy** [comment]
Thank you for your feedback.

I think the `schema.labels["kcl.io/key1"]` is a better one as developers have do in the JSON path e.g. `$.["first.name"]`. This feature will be done in the KCL v0.8.
