### ISSUE TITLE
Add a comparison to Apple's PKL

### ISSUE THREAD

**Issue by nkabir** [kcl-lang/kcl#1028]
Apple recently open-sourced their configuration language, PKL

https://pkl-lang.org/blog/introducing-pkl.html

KCL has an excellent guide comparing other tools. It would be helpful to add PKL to this comparision.

https://kcl-lang.io/docs/user_docs/getting-started/intro/#how-to-choose

**Comment by Peefy** [comment]
Thank you! @nkabir I've added the comparison in this PR https://github.com/kcl-lang/kcl-lang.io/pull/267

If you have any other ideas, please feel free to share them. ❤️

**Comment by nkabir** [comment]
Thank you! I agree with your assessment. And there's no Python integration in Apple's PKL. Python is used extensively in configuration and automation.

**Comment by Peefy** [comment]
Thank you! In the near future, we will also write blogs to comprehensively analyze their differences from the perspectives of scenarios, features and technology.

**Comment by Peefy** [comment]
Closed by https://github.com/kcl-lang/kcl-lang.io/pull/267, will be added more comparison according to this issue: https://github.com/kcl-lang/kcl-lang.io/issues/274
