### ISSUE TITLE
[LFX PreTest] KPM API in rust for IDE integration

### ISSUE THREAD

**Issue by zong-zhe** [kcl-lang/kcl#1031]
## Enhancement

This is the PreTest for https://github.com/kcl-lang/kcl/issues/998.

What you need to do is ncapsulating some of the basic functions of kpm for the IDE to automatically update the dependencies.

You can refer to https://github.com/kcl-lang/kcl/blob/6147b908b52dc1674728bfef3af2002d45a7c478/kclvm/driver/src/kpm_metadata.rs#L60

More details:
- https://kcl-lang.io/docs/tools/cli/package-management/command-reference/update/

**Comment by octonawish-akcodes** [comment]
I have raised a PR here #1032 @zong-zhe

**Comment by d4v1d03** [comment]
I have raised a PR #1040 , though i have added some tests over here, still i am working on those that check dependency updation as i had discussed earlier with you on #998, will try to get them done soon

**Comment by Peefy** [comment]
Closed by #1040
