### ISSUE TITLE
kcl fmt command removes legit code when formatting

### ISSUE THREAD

**Issue by Fdall** [kcl-lang/kcl#1039]
### 1. Minimal reproduce step

When using kcl fmt command on the following file, it removes a whole part of its source code and does not just reformat it:
```
computeItems = lambda a: [str], b: [str], c: [str], item_nb: str -> [str] {
  if (a is Undefined) and (b is Undefined) and (c is Undefined):
    _r: [str] = ["a b and c are undefined"]
  else:
    if a is Undefined:
      a = ["default a value"]
    if b is Undefined:
      b = ["default b value"]
    if c is Undefined:
      c = []
    _r = c + a + b
  _r
}
```

The result I got from the `kcl fmt` command is:
```
computeItems = lambda a: [str], b: [str], c: [str], item_nb: str -> [str] {
    if (a is Undefined) and (b is Undefined) and (c is Undefined):
        _r: [str] = ["a b and c are undefined"]
    elif a is Undefined:
        a = ["default a value"]

    _r
}
```

It looks like every sub statement branches are erased except the first one.
For context, the lambda is used in a Mixin to handle cases where some optional fields are omitted.

### 2. What did you expect to see?

The code should not disappear, formatting the KCL code should be a safe operation.

### 3. What is your KCL components version?

Tested on the latest 0.7.5 version, but I was able to reproduce on older versions (0.6.x).

**Comment by shashank-iitbhu** [comment]
Hey @Peefy just opened a PR for this issue. Please review whenever you get time.
