### ISSUE TITLE
[LFX PreTest] The workflow design of IDE and kpm

### ISSUE THREAD

**Issue by zong-zhe** [kcl-lang/kcl#1058]
## Enhancement

This job is a paper work. The IDE as the place where KCL interacts directly with the user The user experience is very important here. 

By referring to the integration of some mature IDEs and package management tools on the market, and comparing the missing package management functions of KCL IDE, the report primarily includes an analysis of the package management functions employed by mature IDEs. By comparing these well-established projects, it provides a design workflow for KCL IDE’s enhancement.

**Comment by d4v1d03** [comment]
Hey, @zong-zhe, could you please propose a deadline or something for this pre-test and also let me know if i have to submit the report over slack to you or elsewhere.

**Comment by octonawish-akcodes** [comment]
I added the workflow design here #1065 @zong-zhe

**Comment by d4v1d03** [comment]
Hey @zong-zhe @Peefy , i've added the worflow design over here, do have to update it but the initial report has been made - https://docs.google.com/document/d/1sZgrbliM6JVjb79ACoacjG77nhyjzQ5D/edit. Also please suggest do i have to link a PR written in Markdown for the same or just the google doc works.

**Comment by shashank-iitbhu** [comment]
Hey @zong-zhe ! Are there any more Pre tests required to be done for the QUICK FIX project? Let me know if a proposal or design document is required for same?
