### ISSUE TITLE
Unable to use attributes of inferred type

### ISSUE THREAD

**Issue by vtomilov** [kcl-lang/kcl#1066]
## Bug Report

It looks like a bug, but validate please if I'm not doing something illegal.
If you specify type for attribute `b` using `b:str = a or "default"` instead of `b = a or "default"`, it works just fine.

### 1. Minimal reproduce step (Required)
```
schema Foo:
    a: str
    b = a or "default"
    
foo = Foo {
    a: "2"
}

r = foo.b
```
### 2. What did you expect to see? (Required)
```
foo:
  a: '2'
  b: '2'
r: '2'
```

### 3. What did you see instead (Required)
```
error[E2G22]: TypeError
 --> /tmp/sandbox2665606751/prog.k:9:5
  |
9 | r = foo.b
  |     ^ attribute 'b' not found in schema 'Foo'
  |
```

### 4. What is your KCL components version? (Required)
v0.7.0, v0.7.5 also reproduces

**Comment by Peefy** [comment]
Hello @vtomilov Thank you for the feedback. In the current version, this meets expectations and only allows access to properties that use type annotations.

**Comment by vtomilov** [comment]
Ok, thanks!
