### ISSUE TITLE
Expose a way to retrieve value of path_selector if passed

### ISSUE THREAD

**Issue by eshepelyuk** [kcl-lang/kcl#1067]
When `kcl run` is invoked with `-S` flag - it's impossible to get `path_selector` value from KCL code.
It could be good to be able to get this value via `path_selector()` function or any other way.
To be able adjust KCL code behaviour depending on `-S` flag.

**Comment by Peefy** [comment]
Thank you for the feedback. 

KCL currently supports the `-D` flag and the `option()` function to dynamically change code behavior. If you set `-S` and `-D` flags to the same parameter, can it meet your requirements? For example

```python
kcl run main.k -S person -D path_selector=person
```

**Comment by eshepelyuk** [comment]
Yes it will, thanks for suggestion.
