### ISSUE TITLE
Enhancement: add symbol for the decorator in the semantic model.

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl#1068]
## Enhancement

For the following code, there is not hover information for the decorator `@deprefacted`, we need to add the symbol in the semantic DB.

```
@deprecated(version="v1.16", reason="The age attribute was deprecated", strict=True)
schema Person:
    name: str
    age: int
```

**Comment by octonawish-akcodes** [comment]
can i try it?

**Comment by Peefy** [comment]
> can i try it?

Sure! Thank you! ❤️

**Comment by octonawish-akcodes** [comment]
can you provide some more context to this?

**Comment by Peefy** [comment]
@He1pa Can you help add more information?
