### ISSUE TITLE
Union operator incompatible with instances of a schema that have schema arguments

### ISSUE THREAD

**Issue by sshumaker** [kcl-lang/kcl#1084]
## Bug Report

If you add arguments to a schema and use those to assign default values to variables, you cannot union instances of it (or extend instances of it). For some reason the union operator seems to want to want to re-invoke the default args instead of working with the fully formed object.

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
schema Person[separator]:
    firstName: str = "John"
    lastName: str
    fullName: str = firstName + separator + lastName
        
x = Person(" ") {
  lastName = "Doe"
}
y = Person(" ") {
  lastName = "Doe"
}

x | y
```

### 2. What did you expect to see? (Required)

```
  firstName: John
  lastName: Doe
  fullName: John Doe
```

### 3. What did you see instead (Required)
```
4 |     fullName: str = firstName + separator + lastName
  |  unsupported operand type(s) for +: 'str' and 'NoneType'
```

### 4. What is your KCL components version? (Required)
```kcl version 0.7.5```

**Comment by Peefy** [comment]
Thank you! 

This is an unsupported feature that we expect to provide in KCL v0.8 version.

**Comment by sshumaker** [comment]
Thanks. This seems pretty significant? It basically means you cannot union types with schema arguments. I guess the workaround for now is to create lambdas to create your types instead, although that is limiting because it requires a fully formed type.

Is there a way to pass keyword arguments to lambdas? I couldn't figure out how to do that in the documentation.

**Comment by Peefy** [comment]
Make sense!

There are two transitional solutions here, one is to use lambda to build, and the other is to convert the schema to dict

```python
schema Person[separator]:
    firstName: str = "John"
    lastName: str
    fullName: str = firstName + separator + lastName
        
x = Person(" ") {
  lastName = "Doe"
}
y = Person(" ") {
  lastName = "Doe"
}

d = x | {**y}

```

**Comment by Peefy** [comment]
Or we can use the following form:

```python
schema Person[separator]:
    firstName: str = "John"
    lastName: str
    fullName: str = firstName + separator + lastName
        
x = Person(" ") {
  lastName = "Doe"
}
y = Person(" ") {
  lastName = "Doe11c"
}
# Construct a new Person schema. But the new sep `"1"` does not work because the lastName of y is `John Doe11c`
c = Person("1") {
    **x
    **y
}
```

**Comment by sshumaker** [comment]
Ok. This still doesn't work in my use case unfortunately (I'm merging two objects that look like this:
schema State:
  [str]: Field

where Field has the arguments. 

Is there a way to specify the key for a dictionary dynamically? if I could do the equivalent of:

``` state1[key] = state2[key] ``` that might help.

**Comment by Peefy** [comment]
What your case is as follows:

```python
schema State:
    [str]: Person

schema Person[separator]:
    firstName: str = "John"
    lastName: str
    fullName: str = firstName + separator + lastName

state1 = {
    one: Person(" ") {lastName = "Doe"}
}
state2 = {
    two: Person(" ") {lastName = "Doe"}
}
stateUnion = State {
    **state1
    **state2
}
```

or 

```python
schema State:
    [str]: Person

schema Person[separator]:
    firstName: str = "John"
    lastName: str
    fullName: str = firstName + separator + lastName

stateUnion = State {
    one = Person(" ") {lastName = "Doe"}
    two = one
}
```

**Comment by sshumaker** [comment]
The first one.

Interestingly, I just realized the problem was because I had the same key present in both state1 and state2, which is why State {**state1, **state2} wasn't working - although the error printed was actually involving the passed arguments!
