### ISSUE TITLE
issues with check and nested members

### ISSUE THREAD

**Issue by sshumaker** [kcl-lang/kcl#1088]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
schema A:
    index: int

schema B:
    [str]: A
    

schema C:
    b: B
    indices: [int] = [v.index for k,v in b]
    check:
      isunique(indices)
    
C {
  b = B {
    foo = A { index = 4 }
  }    
}
```

### 2. What did you expect to see? (Required)
```
b:
  foo:
    index: 4
indices:
- 4
```

### 3. What did you see instead (Required)
```
EvaluationError
  --> /tmp/sandbox55648969/prog.k:12:1
   |
12 |       isunique(indices)
   |  unsupport hash for undefined
```
### 4. What is your KCL components version? (Required)
kcl version 0.7.5

**Comment by Peefy** [comment]
Thank you for your feedback. It has been fixed in PR https://github.com/kcl-lang/kcl/pull/1077 We have added the Hash function for KCL undefined values.
