### ISSUE TITLE
[Question] GIt Repo support in KCL

### ISSUE THREAD

**Issue by wilsonwang371** [kcl-lang/kcl#1131]
## General Question

Are we able to import a github or gitlab repo now in KCL? I think this is an important feature of a single source of truth in an enterprise environment.

**Comment by Peefy** [comment]
ping @zong-zhe

**Comment by wilsonwang371** [comment]
not sure if `kcl mod add --git` command is ready to use.

**Comment by wilsonwang371** [comment]
![image](https://github.com/kcl-lang/kcl/assets/3913185/0dd7c819-9694-41b8-91dd-ad08148eedff)

![image](https://github.com/kcl-lang/kcl/assets/3913185/b903866e-e60c-479a-b0b8-a19fd5ff80c8)

From what I can see, this seems to be already there. Just want to confirm if this is a complete feature.

**Comment by zong-zhe** [comment]
Hi @wilsonwang371 😄 

This is indeed a meaningful question. The current KCL package management command `kcl mod add` supports adding a **public GitHub repository** as a third-party library dependency by using the `—git` parameter.

For further details on adding a dependency from a Git repository, you may refer to the documentation page: https://kcl-lang.io/docs/tools/cli/package-management/command-reference/add/#add-a-dependency-from-git-repository

Regarding the support for **private GitHub and GitLab repositories**, the work I am currently engaged in addresses this very topic. 

An issue has been created to track the progress of this endeavor: https://github.com/kcl-lang/kpm/issues/255#issuecomment-1991402614

The work on this aspect has now entered the testing phase. It is anticipated that the related PR will be merged within the next day or two.

I have proposed a PR that is in a Work In Progress (WIP) state. https://github.com/kcl-lang/kpm/pull/275

**Comment by wilsonwang371** [comment]
> Hi @wilsonwang371 😄 
> 
> This is indeed a meaningful question. The current KCL package management command `kcl mod add` supports adding a **public GitHub repository** as a third-party library dependency by using the `—git` parameter.
> 
> For further details on adding a dependency from a Git repository, you may refer to the documentation page: https://kcl-lang.io/docs/tools/cli/package-management/command-reference/add/#add-a-dependency-from-git-repository
> 
> Regarding the support for **private GitHub and GitLab repositories**, the work I am currently engaged in addresses this very topic. 
> 
> An issue has been created to track the progress of this endeavor: https://github.com/kcl-lang/kpm/issues/255
> 
> The work on this aspect has now entered the testing phase. It is anticipated that the related PR will be merged within the next day or two.
> 
> I have proposed a PR that is in a Work In Progress (WIP) state. https://github.com/kcl-lang/kpm/pull/275

thanks, i am looking forward to try it

**Comment by wilsonwang371** [comment]
One more question, if I want to use an external module and generate a bunch of objects, what is the best approach? Do I need to do something similar to https://github.com/kcl-lang/konfig/blob/main/examples/appops/nginx-example/dev/kcl.mod ?

Maybe https://github.com/kcl-lang/kcl-lang.io/issues/298#issue-2165083568 is a valid request? example:

```
import modA

objAList = modA.getObjAList()

*objAList

print(modA.ObjA.instances())

```

**Comment by wilsonwang371** [comment]
> In addition, the global variables in the imported KCL Module are accessible but not modifiable, such as

what was the initial design thoughts on this?

**Comment by Peefy** [comment]
> > In addition, the global variables in the imported KCL Module are accessible but not modifiable, such as
> 
> what were the initial design thoughts on this?

This is also limited by the invariance and side effect constraint principles of KCL. For example, if global variables in other modules can be changed, it means that calling functions in other modules may return different results.

**Comment by wilsonwang371** [comment]
> > > In addition, the global variables in the imported KCL Module are accessible but not modifiable, such as
> > 
> > 
> > what were the initial design thoughts on this?
> 
> This is also limited by the invariance and side effect constraint principles of KCL. For example, if global variables in other modules can be changed, it means that calling functions in other modules may return different results.

Make sense. But can there be a better way to solve this? Because global variables in a module should also be global variables.

**Comment by Peefy** [comment]
> Because global variables in a module should also be global variables.

Sorry. I didn't understand the meaning of this sentence. Do you want to access global variables in other modules (including read and write) or export them as YAML/JSON? Can you give me some more specific examples?

**Comment by wilsonwang371** [comment]
> > Because global variables in a module should also be global variables.
> 
> Sorry. I didn't understand the meaning of this sentence. Do you want to access global variables in other modules (including read and write) or export them as YAML/JSON? Can you give me some more specific examples?

Nevermind, I think I need to go though some of the detail implementations later in my environment and give more detail context.

**Comment by wilsonwang371** [comment]
> Hi @wilsonwang371 😄
> 
> This is indeed a meaningful question. The current KCL package management command `kcl mod add` supports adding a **public GitHub repository** as a third-party library dependency by using the `—git` parameter.
> 
> For further details on adding a dependency from a Git repository, you may refer to the documentation page: https://kcl-lang.io/docs/tools/cli/package-management/command-reference/add/#add-a-dependency-from-git-repository
> 
> Regarding the support for **private GitHub and GitLab repositories**, the work I am currently engaged in addresses this very topic.
> 
> An issue has been created to track the progress of this endeavor: [kcl-lang/kpm#255](https://github.com/kcl-lang/kpm/issues/255)
> 
> The work on this aspect has now entered the testing phase. It is anticipated that the related PR will be merged within the next day or two.
> 
> I have proposed a PR that is in a Work In Progress (WIP) state. [kcl-lang/kpm#275](https://github.com/kcl-lang/kpm/pull/275)

BTW, https://github.com/kcl-lang/kpm/pull/275 is a MR to kpm. For kcl, how this part is used during module import?
