### ISSUE TITLE
How can I create a schema with a non-qualified field name?

### ISSUE THREAD

**Issue by steeling** [kcl-lang/kcl#1134]
I want to create a schema that results in the following json:

```json
{
  "$schema": "..."
}
```

How can I create a schema with that as a field?

```python
schema MyObject:
   `$schema`: str
```

**Comment by Peefy** [comment]
Hi @steeling Thank you for the general question. You can see the jsonschema module https://github.com/kcl-lang/modules/blob/main/jsonschema/ty.k to define the "$schema" attribute in KCL v0.8.0
