### ISSUE TITLE
Return types in lambdas?

### ISSUE THREAD

**Issue by steeling** [kcl-lang/kcl#1146]
Looking to get the validation from specifying a return type in lambdas. Is this currently possible?

Something like 

```python
genTile = lambda _manifest: MyType1 {
    ret = MyType2 {
        ....
    }
}.ret
```

Is how I could do this in some other DSL's. Does KCL have some way to specify return types?

**Comment by steeling** [comment]
```
genTile = lambda _manifest: MyType1 => MyType2 {
    ...
}
```

Could be another syntax, unless this is already currently feasible?

**Comment by steeling** [comment]
nvm, answer is to do:

genTile = lambda _manifest: MyType1 {
    MyType2 {
        ....
    }
}

**Comment by Peefy** [comment]
For lambda, KCL will automatically infer your return value type in the function body, although you can explicitly specify it. For example:
```python
f1 = lambda t: Type1 {
    Type2 {}
} # The type of f1 is (Type1) -> Type2

f2 = lambda t: Type1 -> Type2 {
    Type2 {}
} # The type of f2 is (Type1) -> Type2
```
