### ISSUE TITLE
kcl mod not exist

### ISSUE THREAD

**Issue by reckless-huang** [kcl-lang/kcl#1147]
<img width="808" alt="image" src="https://github.com/kcl-lang/kcl/assets/53162954/d88c00ec-9513-4eb0-807c-7b96b209162d">

<img width="611" alt="image" src="https://github.com/kcl-lang/kcl/assets/53162954/2bc50180-efe5-4142-aeed-8f6d4062c2b6">

refer doc
https://www.kcl-lang.io/docs/user_docs/guides/package-management/quick-start

**Comment by Peefy** [comment]
Hello @reckless-huang  What is your KCL version? Is the latest version v0.8.x or 0.7.x ?

**Comment by reckless-huang** [comment]
<img width="578" alt="image" src="https://github.com/kcl-lang/kcl/assets/53162954/2dcb2fa8-363c-41d9-a423-7eb6939bd38b">
Because kcl-go will use the local kcl, and the kcl installed via brew doesn’t seem to be the latest version, I manually downloaded the kcl-cli from the release page.

It seems like they might not be the same  tool？

**Comment by Peefy** [comment]
You've downloaded from here? https://github.com/kcl-lang/cli or https://www.kcl-lang.io/docs/user_docs/getting-started/install?

**Comment by reckless-huang** [comment]
Sorry, I think I must have downloaded from the wrong repository.
