### ISSUE TITLE
Problem with nested loop

### ISSUE THREAD

**Issue by wilsonwang371** [kcl-lang/kcl#1161]
## General Question

![image](https://github.com/kcl-lang/kcl/assets/3913185/de38f552-6578-49c6-aa83-3f8d3c946bdd)

There are two issues:

1. Ideally, if i have two loops iterate each element in `[[a, b, c], [1, 2, 3], ..]`. The expression is more natural if it is like this: `[do(item) for item in sublist for sublist in list]`. However, it seems like in KCL, we have to do `[do(item) for sublist in list for item in sublist]`
2. If the list can be something like `[[a, b, c], [1, 2, 3], Undefined, ..]` and I want to filter out the Undefined item. I will get error even if I do it like this `[do(item) for sublist in list if sublist != Undefined for item in sublist]`

How do we resolve the problem in the 2nd question? Do we have plans to make the expression change in question 1?

**Comment by Peefy** [comment]
For the question 2. You can use `[do(item) for sublist in list for item in sublist if sublist]` Note that `if sublist` works well. See  https://www.kcl-lang.io/docs/user_docs/support/faq-kcl#11-how-to-judge-whether-a-variable-is-noneundefined-and-whether-a-stringdictlist-is-empty

For the question 1. A good question. For loop expressions, we have followed the Python grammar and semantic, so it will not change in the short term. However, we will explore more easily understandable loop bodies in configuration and policy scenarios.
