### ISSUE TITLE
kcl-lsp scoop config version not in alignment with latest kcl scoop config

### ISSUE THREAD

**Issue by markphillips100** [kcl-lang/kcl#1165]
Should the scoop [config](https://github.com/kcl-lang/scoop-bucket/blob/main/Scoops/kcl-lsp.json) for kcl-lsp be updated to 0.8.2?

My scoop-installed kcl is 0.8.2 but my kcl-language-server is 0.8.0.  I don't know if this is the reason why my intellisense is not working in vscode?  I could install the binaries direct via powershell but prefer scoop from an easy upgrade point of view.

**Comment by Peefy** [comment]
Hello. The reason why the version of kcl language server is 0.8.0 is that we found some issues in versions 0.8.1 and 0.8.2, so it was not released. This should not affect your local kcl language server 0.8.0. Can you ensure that kcl-language-server is in your PATH?

@He1pa Can you help follow up on this issue?

**Comment by markphillips100** [comment]
Hi @Peefy .  Yeah it is in the path.

**Comment by markphillips100** [comment]
FYI from powershell prompt I type `(get-command kcl-language-server.exe).Path` and get the following path found:
```
C:\Users\mark_\scoop\shims\kcl-language-server.exe
```

**Comment by He1pa** [comment]
0.8.0 also works fine.
You can check the kcl lsp version through `kcl-language-server version` and check whether it is in the path. In addition, you can check whether vscode and lsp are communicating normally here
![image](https://github.com/kcl-lang/kcl/assets/56333845/6373898b-68be-4360-9b95-93fe35e8d749)

**Comment by markphillips100** [comment]
Thanks for that @He1pa.  I think it's something to do with maybe how I'm structuring the module.

Whatever it is I get a message "Not a valid kcl path, request failed" in the kcl language server log output.  Just trying to create a minimal repro.

**Comment by markphillips100** [comment]
It's hard to pinpoint as once the "Not a valid kcl path, request failed" message appears in log it doesn't seem to come good even when I revert code back to a known working minimal setup.  I've tried shutting down all vscode but not sure that's enough.  Is there a way to reset the server explicitly?

**Comment by markphillips100** [comment]
So I have an example with minimal code [here](https://github.com/markphillips100/kcllsp-test).

For me on windows vscode I have no colouring on the configSchemas.ConfigSchema as you can see here 
![image](https://github.com/kcl-lang/kcl/assets/6239029/80bf9840-2af4-4dee-90a0-df87174ae01a)

I see lots of the same error in log immediately after starting the one and only vscode running.  F12 on ConfigSchema gives me no definition:

![image](https://github.com/kcl-lang/kcl/assets/6239029/e8fd020c-d677-4cfa-86dd-458867eb4424)

```
[Info  - 4:12:33 PM] Not a valid kcl path, request failed
thread '<unnamed>' panicked at sema\src\core\global_state.rs:514:66:
called `Option::unwrap()` on a `None` value
[Info  - 4:12:33 PM] on request Request { id: RequestId(I32(33)), method: "textDocument/codeAction", params: Object {"context": Object {"diagnostics": Array [], "triggerKind": Number(2)}, "range": Object {"end": Object {"character": Number(0), "line": Number(6)}, "start": Object {"character": Number(0), "line": Number(6)}}, "textDocument": Object {"uri": String("file:///d%3A/Dev/github/kcl-test/main.k")}} }
[Info  - 4:12:33 PM] on request Request { id: RequestId(I32(34)), method: "textDocument/semanticTokens/full", params: Object {"textDocument": Object {"uri": String("file:///d%3A/Dev/github/kcl-test/main.k")}} }
[Info  - 4:12:33 PM] Not a valid kcl path, request failed
[Info  - 4:14:22 PM] on notification Notification { method: "$/setTrace", params: Object {"value": String("off")} }
[Info  - 4:14:39 PM] on request Request { id: RequestId(I32(35)), method: "textDocument/hover", params: Object {"position": Object {"character": Number(23), "line": Number(2)}, "textDocument": Object {"uri": String("file:///d%3A/Dev/github/kcl-test/main.k")}} }
[Info  - 4:14:39 PM] Not a valid kcl path, request failed
[Info  - 4:16:21 PM] on request Request { id: RequestId(I32(36)), method: "textDocument/hover", params: Object {"position": Object {"character": Number(72), "line": Number(2)}, "textDocument": Object {"uri": String("file:///d%3A/Dev/github/kcl-test/main.k")}} }
[Info  - 4:16:21 PM] Not a valid kcl path, request failed
[Info  - 4:16:21 PM] on request Request { id: RequestId(I32(37)), method: "textDocument/hover", params: Object {"position": Object {"character": Number(71), "line": Number(2)}, "textDocument": Object {"uri": String("file:///d%3A/Dev/github/kcl-test/main.k")}} }
[Info  - 4:16:21 PM] Not a valid kcl path, request failed
```

**Comment by Peefy** [comment]
cc @He1pa

**Comment by markphillips100** [comment]
I think my example is working now so possible false repro.  It's very hard to pin down why the error occurs but when it does there seems to be no correlation with what makes things work again.  Maybe it's a windows environment only thing to perhaps.

**Comment by He1pa** [comment]
> I think my example is working now so possible false repro. It's very hard to pin down why the error occurs but when it does there seems to be no correlation with what makes things work again. Maybe it's a windows environment only thing to perhaps.

It has nothing to do with windows, this is a problem of lsp implementation. I've optimized this error message in the new implementation.

Is there any other way you can update to the new version?

**Comment by markphillips100** [comment]
I can remove the scoop installs and do the powershell install method.  What's the new version?

**Comment by He1pa** [comment]
> I can remove the scoop installs and do the powershell install method. What's the new version?

0.8.1 or 0.8.2

**Comment by markphillips100** [comment]
okay, I'll try in a few hours.  Thanks for the update

**Comment by markphillips100** [comment]
I've been driving 0.8.2 kcl-lsp for over an hour of numerous kcl file edits and not seeing the issue.  I am playing with a slightly modified folder structure so don't know if that's the reason or not.

I have a fair bit of KCL code to write and test over the next few days so will report back on how that went, or sooner if the problem reappears.

Thanks for your help so far @He1pa and @Peefy

**Comment by Peefy** [comment]
Thank you again for your feedback. We will also strive to update a more stable and better performing version. ❤️

**Comment by Peefy** [comment]
Closed by https://github.com/kcl-lang/scoop-bucket/commit/3c3407a0e67f2f94082b56b4f5892c4641d371a6
