### ISSUE TITLE
Consistent iteration order of dict

### ISSUE THREAD

**Issue by steeling** [kcl-lang/kcl#1178]
It would be nice to have a consistent iteration order for dicts.

```
order = [v for k, v in {...}]
```

This would simplify a lot of config management, ie: for denormalized lists where we need to take a dict and create a list. And would also help prevent diffs in gitops related scenarios

**Comment by Peefy** [comment]
Sorry In KCL, the dict is ordered and have a consistent iteration order. Cloud you please give more examples?

**Comment by steeling** [comment]
Yes, my apologies, had a mixup on my end, sorry for the noise!
