### ISSUE TITLE
kcl on a dir doesn't lazy eval properly

### ISSUE THREAD

**Issue by steeling** [kcl-lang/kcl#1253]
### 1. Minimal reproduce step (Required)

test/versions.k:
```python
version = "v1.0.0"
```

in  test/main.k:

```
app = {
   version = version   
}
```

then try again and rename `version.k` so that it lexicographically comes before `main.k`, ie: `test/_versions.k`

### 2. What did you expect to see? (Required)

```
version: v1.0.0
app:
  version: v1.0.0
```

due to proper lazy eval

### 3. What did you see instead (Required)

app: {}
version: v1.0.0

### 4. What is your KCL components version? (Required)

kcl version
0.8.3-darwin-arm64

**Comment by Peefy** [comment]
Thanks for the feedback. This is a WIP feature. https://github.com/kcl-lang/kcl/pull/1104

It is expected to be in v0.9
