### ISSUE TITLE
[bug] file mkdir and delete don't seem to work

### ISSUE THREAD

**Issue by dennybaa** [kcl-lang/kcl#1300]
Hello @Peefy and @shruti2522 , I've tried #1271 

it doesn't seem to work. I'm also confused should not this be a part of CLI, but nonetheless I'm evidently not aware of the architecture. Should be [kclvm v0.8.7](https://github.com/kcl-lang/kcl/releases/tag/v0.8.7) installed somehow separately? As of language server (in my case it's inside a toolbox container) and vscode ext they suggest both `delete` and `mkdir` functions. Cli is separate on the host... Both cli and language server have been updated.

Thank you!

### 1. Minimal reproduce step (Required)

a.k:
```
import file

file.mkdir("hello", False)
```

### 3. What did you see instead (Required)

```
kcl a.k
Error: failed to compile the kcl package

error[E2G22]: TypeError
 --> /home/dennybaa/code/p2p/iaas-alerting/a.k:3:1
  |
3 | file.mkdir("hello", False)
  | ^ attribute 'mkdir' not found in 'module 'file''
```

### 4. What is your KCL components version? (Required)

kcl version
0.8.7-linux-amd64

**Comment by Peefy** [comment]
@dennybaa Sorry, I have only released a new version of the language server so far, and the CLI has not yet completed the release of the new version. After resolving some other issues such as #1294 , the release will be completed.

**Comment by dennybaa** [comment]
@Peefy oh no problem, thanks a lot🙏🏻

**Comment by Peefy** [comment]
Released in https://github.com/kcl-lang/cli/releases/tag/v0.8.8
