### ISSUE TITLE
[bug] lsp hover content  error

### ISSUE THREAD

**Issue by He1pa** [kcl-lang/kcl#1303]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
schema with param and base
![image](https://github.com/kcl-lang/kcl/assets/56333845/659d549b-c198-436f-96e9-5165d2eac69f)

### 2. What did you expect to see? (Required)
```
main
---
schema Data1[n: str](Data):
---
Attrbutes:
name: str
```

**Comment by shruti2522** [comment]
Hey @He1pa, I'd love to work on this. Could you please assign it to me?
