### ISSUE TITLE
[Enhancement] IDE completion items in the lambda internal scope.

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl#1352]
## Enhancement

For the following code:

![image](https://github.com/kcl-lang/kcl/assets/22744597/73f1a1f4-7373-4736-b55d-7b563d009b2f)

The expect the completion items is `["case", "cases"]` instead of ["cases"]

**Comment by coderquill** [comment]
Hello @Peefy 
I am Rupali. Would like to work on this issue. Please assign it to me. 
Also, is there a slack channel that I can join for this project?

**Comment by coderquill** [comment]
Awesome, Thanks a bunch!

**Comment by Ari1009** [comment]
> @Ari1009 @coderquill You should join the CNCF slack firstly. ![image](https://private-user-images.githubusercontent.com/22744597/334322774-1396d3f7-4256-48ea-9473-96c2dc163fb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4ODU4MDksIm5iZiI6MTcxNjg4NTUwOSwicGF0aCI6Ii8yMjc0NDU5Ny8zMzQzMjI3NzQtMTM5NmQzZjctNDI1Ni00OGVhLTk0NzMtOTZjMmRjMTYzZmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA4MzgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNjQ5ZGZmZjcwOTliYWExMGRkYmM0YTU4OWFiOWNkMzk0YjdmZDNiYWI2MmIxN2Q1NWEyZWRlZTlmNTNhYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.81mXA6iU_CVuzlwJKYER63eXQGoLSs0rYQsUBk4kmII)

Thankss!!

**Comment by EraKin575** [comment]
Is this issue being worked upon?
