### ISSUE TITLE
[Enhancement] The KCL testing tool supports testing incorrect failure cases, such as schema check conditions using the runtime.catch function

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl#1385]
For exampla

+ main.k

```python
schema Name:
    count: int

    check:
        count > 10
```

+ main_test.k

```python
import runtime

test_name_schema_failed = lambda {
    assert "Schema check failed" in runtime.catch(lambda {Name{count: 10}}
}
```

**Comment by Wck-iipi** [comment]
@Peefy Can I work on this issue?

**Comment by Wck-iipi** [comment]
@Peefy I tried kcl test after building kcl but none of the subcommands with kcl are currently working. I am currently on MacOS 14.5. The only subcommands that I am being shown are run, server, version and help.
<img width="1154" alt="image" src="https://github.com/kcl-lang/kcl/assets/110763795/e9d93a03-3b05-4126-b9c0-b1faf6b7c340">

Even the make doesn't show any errors.
<img width="1154" alt="image" src="https://github.com/kcl-lang/kcl/assets/110763795/7cab1e5d-e577-46c3-8565-efc7f10703af">

Below is my zshrc file which has set kcl as alias for kclvm_cli.
<img width="1154" alt="image" src="https://github.com/kcl-lang/kcl/assets/110763795/4b026b16-3988-4de6-b049-b53f0fea7219">

Moreover, even testing package cannot be imported.
<img width="1148" alt="image" src="https://github.com/kcl-lang/kcl/assets/110763795/c628613d-3c7d-48e1-86f5-fd9d9986c060">

Any idea why I can't see any subcommands or I cannot import testing? Have I not installed something? Thanks for the help.

**Comment by Wck-iipi** [comment]
@Peefy Thanks for responding. Could you tell me where I have to write this `catch_err` code at? Would it be at /tools/src/testing? I am a little confused with the implementation.
Also, when I finally create the `catch_err` function, how would user use that function?

**Comment by Wck-iipi** [comment]
@Peefy Could you give me some references that would tell me more about this(like some PR where you have created/modified compiler runtime plugin or testing system module)? Because upon searching `import testing`, I came across some examples like [this](https://github.com/kcl-lang/kcl/issues/178), which is useful, but I would like if you could guide me more. Thanks.
