### ISSUE TITLE
[Enhancement] Add hover information when input the function argument

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl#1398]
## Enhancement

Like Rust

![image](https://github.com/kcl-lang/kcl/assets/22744597/a7f96fb8-90a9-464f-8155-5d62fdfb0d0f)

When developers type the function parameters in the code.

```python
func = lambda x, y, z {
    x + y + z
}
res = func(x, <cursor>) # Show the function type hover information and the parameter location.
```

**Comment by EraKin575** [comment]
I would like to work on this issue
