### ISSUE TITLE
[Enhancement] Enhance highlighting of nested quotes in long strings.

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl#1403]
For the following code, the chars in the long string should have consistent highlight.
```
aaa = """
"a" 'a' "a"
"""
bbb = """ "a" """
ccc = ''' "a" 'a' '''
```

![image](https://github.com/kcl-lang/kcl/assets/22744597/2a9f37fb-b573-4f6e-8e96-8b4b5ce003b0)

**Comment by cy00r** [comment]
Hey, can I work on this issue?

**Comment by cy00r** [comment]
@Peefy 
Hey, can you please highlight/ping the code section where I have to make changes?

**Comment by He1pa** [comment]
> @Peefy Hey, can you please highlight/ping the code section where I have to make changes?

@cy00r  
sema/core/symbol, consider use a new symbol kind to represent long string,  
sema/namer/node.rs and sema/advanced_resolver/node.rs to update symbol
you can ref other kind of symbol

**Comment by Gmin2** [comment]
@cy00r are yu still working on it ?

**Comment by cy00r** [comment]
@Gmin2 Yes I'm.

**Comment by cy00r** [comment]
Hey, @Gmin2 you can work on this.

**Comment by Gmin2** [comment]
on it @Peefy

**Comment by Gmin2** [comment]
Hey @Peefy, am really sorry at the moment i am out of my hometown for 2-3 week, thats why have removed my assignment so that other contributor can give it a try
