### ISSUE TITLE
kcl run split stderr and stdout ?

### ISSUE THREAD

**Issue by atelsier** [kcl-lang/kcl#1406]
## General Question

Hello, i have to do this to make yq work after a `kcl run` invocation:

```
kcl run oci://ghcr.io/kcl-lang/podinfo -D replicas=2 | tail +3 | yq
```

Would it be possible to send information logs to stderr and yaml data to stdout ?

```
kcl run oci://ghcr.io/kcl-lang/podinfo -D replicas=2 | head -2
the lastest version '0.1.1' will be pulled
pulling '/kcl-lang/podinfo:0.1.1' from 'ghcr.io/kcl-lang/podinfo'
```

**Comment by atelsier** [comment]
i was hoping for `2>/dev/null > temp.yaml` instead of `-q` and `-o file.yaml`

thanks @Peefy

**Comment by diefans** [comment]
I was also running into this, since it breaks with what every other CLI tool is promising - IMHO the mapping of payload to `stdout` and logs to `stderr` is state of the art in CLI applications.
