### ISSUE TITLE
Publish KCL extension to https://open-vsx.org/

### ISSUE THREAD

**Issue by borgius** [kcl-lang/kcl#1495]
Feature Request

When using [code server](https://github.com/coder/code-server) (the browser version of VSCode), it currently utilizes the open-vsx registry for extensions. It would be much appreciated if you could also make your fantastic extensions available on this registry for use with code server.

**Comment by He1pa** [comment]
thank you for your feedback. I have published it to open-vsx and you can install it now
![image](https://github.com/user-attachments/assets/3c6384c3-d7d5-49c4-bdaa-64c485cedbf1)

![image](https://github.com/user-attachments/assets/75638272-dc76-4df1-98a6-b7a895eb5793)
