### ISSUE TITLE
[Bug] Completion items lost schema attribute in the schema body

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl#1556]
![image](https://github.com/user-attachments/assets/b2a9eab4-572d-484d-b595-0df831d1798a)

The expected completion items contain `name`

KCL Language Server version:

```
Version: 0.10.0-alpha.2-c020ab3eb4b9179219d6837a57f5d323
Platform: aarch64-apple-darwin
GitCommit: cb2beb47ce6b6d0ceef9d81e39aba0b0700a2677
```

**Comment by He1pa** [comment]
fix and add ut in https://github.com/kcl-lang/kcl/pull/1541
