### ISSUE TITLE
Can't run kcl from java

### ISSUE THREAD

**Issue by xnull** [kcl-lang/kcl#1771]
I'm trying to run a java app with kcl and it fails.
Here is the code:
```
package com.example;

import com.kcl.api.API;
import com.kcl.api.Spec.ExecProgram_Args;
import com.kcl.api.Spec.ExecProgram_Result;

public class Main {

    public static void main(String[] args) throws Exception {
        API api = new API();
        ExecProgram_Args kclArgs = ExecProgram_Args.newBuilder()
                //.addKFilenameList("kcl.k")
                .build();
        ExecProgram_Result result = api.execProgram(kclArgs);
        System.out.println(result.getYamlResult());
    }
}
```

Error:
```
> Task :clustering:run
Exception in thread "main" java.lang.Error: a06f
        at com.kcl.api.API.call(API.java:654)
        at com.kcl.api.API.execProgram(API.java:296)
        at com.example.Main.main(Main.java:14)
```

It looks like kcl is trying to load a native library and fails. It's unclear what is going on inside.
P.S. I tried to run it on mac and linux, the result is the same.

**Comment by xnull** [comment]
Hey guys, any thoughts?

**Comment by zong-zhe** [comment]
> any

Hi @xnull 😄 

Thanks for your feedback; I am trying to troubleshoot the issue; could you provide your `pom.xml` part about KCL? I need some version information to help me find the problem.

**Comment by zong-zhe** [comment]
> addKFilenameList

Hi @xnull 😄 

I found this problem: the format of the information is wrong; you did not specify the file to compile in the passed arguments, and it outputs a diagnostic message `ERROR:No input KCL files or paths`; this message outputs the wrong format in the java SDK. I will fix this soon. You can temporarily workaround by checking that the incoming path is not empty before calling that API now, thanks again for your feedback.

**Comment by xnull** [comment]
> > addKFilenameList
> I found this problem...

Hi Zong, thank you very much for the help. 
Yes, I just reproduced the issue on a fresh hello-world project, and the problem was - when it can't find a *.k file it fails with the error. As simple as that. 
So, just having an error message will help avoid being confused with the error.
