### ISSUE TITLE
`kcl mod pull` fails across filesystem boundaries

### ISSUE THREAD

**Issue by mproffitt** [kcl-lang/kcl#1775]
## Bug Report

When trying to run `kcl mod pull` where `/tmp` is on a different filesystem to the module being built, the pull command fails with `invalid cross-device link`

I believe that this comes from https://github.com/kcl-lang/kcl/blob/367cba9e6849337a95e13ce5e3f54784d708f157/kclvm/runtime/src/file/mod.rs#L247 

however `fs::rename` does not work across filesystem boundaries as it only performs a simple rename, leaving the data in place on disk rather than completely moving it to the new location.

### 1. Minimal reproduce step (Required)

The simplest way to test this is to run KCL in a docker container using a bind mount to the local directory

```bash
mkdir kcltest && cd kcltest
docker run -it \
    --mount type=bind,source="$(pwd)",target=/test \
    --name kcltest kcllang/kcl:latest sh -c 'cd test; kcl mod pull k8s'
```

### 2. What did you expect to see? (Required)

The `k8s` module should be added at `oci/ghcr.io/kcl-lang/k8s`

### 3. What did you see instead (Required)

The pull command fails with `invalid cross-device link`

```nohighlight
start to pull oci://ghcr.io/kcl-lang/k8s
the lastest version '1.31.2' will be downloaded
downloading 'kcl-lang/k8s:1.31.2' from 'ghcr.io/kcl-lang/k8s:1.31.2'
rename /tmp/1154039051/git oci/ghcr.io/kcl-lang/k8s: invalid cross-device link
```

### 4. What is your KCL components version? (Required)

N/A

EDIT:

> [!Note]
> Whilst this can be mitigated by setting the value of `TMPDIR` to a  location on the same filesystem as the current module, this feels more like a workaround than a viable long term solution.
>
> For example, the following works:
> 
> ```bash
> mkdir -p kcltest/tmp && cd kcltest
> docker run -it \
>    --mount type=bind,source="$(pwd)",target=/test \
>    --name kcltest kcllang/kcl:latest sh -c 'cd test; TMPDIR=/test/tmp kcl mod pull k8s'
> start to pull oci://ghcr.io/kcl-lang/k8s
> the lastest version '1.31.2' will be downloaded
> downloading 'kcl-lang/k8s:1.31.2' from 'ghcr.io/kcl-lang/k8s:1.31.2'
> pulled k8s 1.31.2 successfully
> ```

**Comment by zong-zhe** [comment]
Hi @mproffitt 😄 

I failed to reproduce this problem in v0.11.0-alpha.1, 

This is a screenshot of my execution:

<img width="512" alt="Screenshot 2024-12-16 at 16 46 04" src="https://github.com/user-attachments/assets/511e6ede-a9d4-44ec-8182-289d91c452bb" />

The code responsible for pulling the KCL tripartite library is not in this repository. In this PR https://github.com/kcl-lang/kpm/pull/567, I will try to replace the `os.Rename` method with the `utils.MoveOrCopy` method and use a rollback. If rename fails, It will use copy.

And this is my debug version:

<img width="512" alt="Screenshot 2024-12-16 at 16 47 18" src="https://github.com/user-attachments/assets/12edbb9b-a442-463b-af11-c8db76816a74" />
