### ISSUE TITLE
Maybe unsound in c2str_vec

### ISSUE THREAD

**Issue by lwz23** [kcl-lang/kcl#1776]
hello, thank you for your contribution in this project, I am scanning the unsoundness problem in rust project.
I notice the following code:
```
pub fn c2str_vec(ptr_array: *const *const c_char) -> Vec<String> {
    let mut result = Vec::new();
    let mut index = 0;

    unsafe {
        loop {
            let current_ptr = *ptr_array.offset(index);
            if current_ptr.is_null() {
                break;
            }
            let c_str = std::ffi::CStr::from_ptr(current_ptr);
            let rust_string = c_str.to_string_lossy().to_string();
            result.push(rust_string);
            index += 1;
        }
    }

    result
}
```
Considering `pub mod api` and this is a `pub` function, I assume user can directly call to this function, if it's this case , I think there may exist a unsound problem in this code, eg. maybe ptr_array is null pointer? It will lead to UB. I suggest mark this function as unsafe or add additional check to varify the pointer. I chose to report this issue for security reasons, but please don't mind if the function is not intended for external use and should be marked as pub(crate), or if this is an error report and there is actually no unsound problem.

**Comment by He1pa** [comment]
Thanks for your suggestion, I will review this code

**Comment by He1pa** [comment]
As far as I know, derefer a null pointer in Rust will cause panic, not ub. But I think it is reasonable to change to pub(crate). If you have a better suggestion, thank you for any kind contribution.

**Comment by lwz23** [comment]
Thank you for your response! I appreciate your insights. However, I would like to clarify that dereferencing a null pointer in Rust does not cause a `unwinding panic` but instead results in an `abort`, this is a long story to tell the difference........ But in short, as this action is considered undefined behavior (UB) according to Rust's safety guarantees. This is because null pointer dereferencing violates Rust's memory safety rules, and the compiler does not insert runtime checks for such cases. I hope this explanation helps, and I look forward to contributing further!

**Comment by lwz23** [comment]
By the way, if you can confirm that all calls to `c2str_vec` are internal and trustworthy, such as ensuring that no null pointers are involved, then marking `c2str_vec` as `pub(crate)` would be sufficient. However, if the reliability of `ptr`'s source cannot be guaranteed, I would suggest the following:  
1. Mark the function as `unsafe` and add documentation to clarify that the caller is responsible for ensuring safety.  
2. Add internal checks to verify that `ptr` is valid.  

I hope this suggestion is helpful!

**Comment by He1pa** [comment]
> Thank you for your response! I appreciate your insights. However, I would like to clarify that dereferencing a null pointer in Rust does not cause a `unwinding panic` but instead results in an `abort`, this is a long story to tell the difference........ But in short, as this action is considered undefined behavior (UB) according to Rust's safety guarantees. This is because null pointer dereferencing violates Rust's memory safety rules, and the compiler does not insert runtime checks for such cases. I hope this explanation helps, and I look forward to contributing further!

Thanks for your advice. I did a simple test.
```#[test]
fn test_c2str_vec_null_ptr() {
    let ptr_array: *const *const c_char = std::ptr::null();

    let result = c2str_vec(ptr_array);

    assert!(result.is_empty(), "The result should be an empty array");
}
```
and i got
`process didn't exit successfully: kcl/kclvm/target/debug/deps/kclvm_runtime-338e7c8890527cc1 'api::utils::test_c2str_vec_null_ptr' --exact --show-output (signal: 11, SIGSEGV: invalid memory reference)`

I'm not very familiar with this, maybe I should learn more about this :) 
But now I have no idea how to check if ptr is valid. Do you have some examples, or can you just submit a PR to modify them directly?

**Comment by lwz23** [comment]
If you think option 2 is more appropriate, then I'm happy to submit a PR because it doesn't involve refactoring the code elsewhere. Haha.

**Comment by He1pa** [comment]
cc @zong-zhe  what do you think about it? I prefer option 2

**Comment by zong-zhe** [comment]
Hi @lwz23 @He1pa   😄 

Oh, this is really cool! The second option is better.

And we are actively seeking the community's support to help us build the KCL community together. If you, @lwz23, as a tech expert, are interested, you are more than welcome to submit a PR to help us add this part. We welcome you to join us as a contributor to KCL. Furthermore, we could invite you to become a community maintainer if opportunities arise.

Thanks again for the feedback you provided for KCL; it has immensely benefited us. 👍👍👍

**Comment by lwz23** [comment]
Thanks for your trust! I will submit a PR to fix this issue. And I am happy to contribue to KCL in the future.

**Comment by lwz23** [comment]
In the same rs file I found the following code:
```
/// Copy str to mutable pointer with length
pub(crate) fn copy_str_to(v: &str, p: *mut c_char, size: *mut kclvm_size_t) {
    unsafe {
        let c_str_ptr = v.as_ptr() as *const c_char;
        let c_str_len = v.len() as i32;
        if c_str_len <= *size {
            std::ptr::copy(c_str_ptr, p, c_str_len as usize);
            *size = c_str_len
        }
    }
}

/// Convert a C str pointer to a Rust &str.
/// Safety: The caller must ensure that `s` is a valid null-terminated C string.
pub fn c2str<'a>(p: *const c_char) -> &'a str {
    let s = unsafe { std::ffi::CStr::from_ptr(p) }.to_str().unwrap();
    s
}
```
It seems to me that there is also the possibility of a null pointer. Especially this part is very strange to me:
```
/// Convert a C str pointer to a Rust &str.
/// Safety: The caller must ensure that `s` is a valid null-terminated C string.
pub fn c2str<'a>(p: *const c_char) -> &'a str {
    let s = unsafe { std::ffi::CStr::from_ptr(p) }.to_str().unwrap();
    s
}
```
In Rust, it is generally expected that if a `/// Safety` comment is explicitly provided, the function should either be marked as `unsafe`, or it should include internal checks to ensure safety, accompanied by a `// Safety` comment explaining the rationale. This particular section, however, seems to deviate from both conventions. It neither guarantees that the operation is entirely safe nor marks the function as `unsafe`. Perhaps I should also consider adding `assert` checks in these parts for clarity and safety? Do you think that's reasonable?

**Comment by lwz23** [comment]
I have submitted a PR to address this issue. If you find anything that could be improved or adjusted, please feel free to either modify it directly in the PR or let me know your suggestions.

**Comment by zong-zhe** [comment]
cc @He1pa , we need to review at this PR together
