### ISSUE TITLE
[cli] kcl.mod file auto created when no root path is found

### ISSUE THREAD

**Issue by zflat** [kcl-lang/kcl#1788]
## General Question

When I run the `kcl run path/to/files` command from a directory that does not contain a root path, `kcl.mod` and `kcl.mod.lock` files are generated in the directory specified on the command line path to run. However, I did not intend for the specified path to become a root path and it can be unclear why it is being treated as one. Why does the `kcl.mod` file get created automatically? Is there any way to change this default behavior so that I don't have files auto generated in places I don't expect and that will affect the results of running `kcl` code?

**Comment by zong-zhe** [comment]
Hi @zflat 😄 

We have confirmed that this is a bug in version 0.11.0-alpha.1, and we are fixing it. We are curious to know whether it also exists in other versions. If you are not in version 0.11.0-alpha.1, please give me your version number. To help me better capture this problem. Thanks !
