### ISSUE TITLE
High CPU Usage by `kcl-language-server`

### ISSUE THREAD

**Issue by eminaktas** [kcl-lang/kcl#1789]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Use VSCode for development with `kcl` and `kcl-language-server` installed.
2. Leave the laptop in sleep mode instead of shutting it down regularly.
3. Observe high CPU usage by `kcl-language-server` over time.

<img width="231" alt="Screenshot 2024-12-14 at 05 58 38" src="https://github.com/user-attachments/assets/51c07269-d8a3-4ec2-8fba-02a24dbf290e" />

<img width="789" alt="Screenshot 2024-12-14 at 05 57 28" src="https://github.com/user-attachments/assets/b9fca604-5c38-494e-850d-961fac004791" />

### 2. What did you expect to see? (Required)

No or minimal CPU usage from `kcl-language-server`, especially when VSCode is idle, and the laptop is not actively being used.

### 3. What did you see instead (Required)

• Persistent high CPU usage by `kcl-language-server`, causing the laptop to heat up significantly.
• Even when the laptop lid is closed, the CPU consumption continues, leading to excessive battery drain and heat.
•After killing the process and restarting VSCode, the high CPU usage stops, but `kcl-language-server` no longer functions correctly. After 2 hours, it stays like this in this screenshot. <img width="868" alt="Screenshot 2024-12-14 at 06 43 17" src="https://github.com/user-attachments/assets/6b39873d-2acf-4fcb-b863-640d732ce837" />

### 4. What is your KCL components version? (Required)

```bash
kcl-language-server  version
Version: 0.10.8-c020ab3eb4b9179219d6837a57f5d323
Platform: aarch64-apple-darwin
GitCommit: 2aa8feac72df509fa7b48cd6d339cc68038644d4
```

```bash
kcl version
0.11.0-alpha.1-darwin-arm64
```

**Comment by eminaktas** [comment]
Please let me know If I can provide any more information to help you.

Since I had the alpha version for `kcl`, I downgraded to `0.10.8`. After downgrade it started to work as expected.

To downgrade, I first removed existing `kcl` and `kcl-language-server`. The, re-installed with `0.10.8` version for both binaries.

```bash
kcl version
0.10.8-darwin-arm64
~ kcl-language-server version
Version: 0.10.8-c020ab3eb4b9179219d6837a57f5d323
Platform: aarch64-apple-darwin
GitCommit: 2aa8feac72df509fa7b48cd6d339cc68038644d4
```

**Comment by He1pa** [comment]
I've noticed this issue and am working on a fix.

**Comment by He1pa** [comment]
New features developed in the IDE will trigger dependency updates (kcl mod metadata --update) based on changes in the kcl.mod file, but this command will format kcl.mod and rewrote it. This caused a loop.
I temporarily disabled this feature
