### ISSUE TITLE
[Enhancement] All rust code needs to be fixed by executing `cargo clippy --fix --allow-dirty`

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl#191]
## Enhancement

All rust code needs to be fixed by executing `cargo clippy --fix --allow-dirty`.

**Comment by zong-zhe** [comment]
clippy KCLVM/compiler_base - https://github.com/KusionStack/KCLVM/pull/194

**Comment by octonawish-akcodes** [comment]
does this means after running the command, removing the unnecessary code or updating it? @Peefy

**Comment by Peefy** [comment]
> does this means after running the command, removing the unnecessary code or updating it? @Peefy

Yes. 👍
