### ISSUE TITLE
Internal Unsoundness

### ISSUE THREAD

**Issue by Nugine** [kcl-lang/kcl#196]
<https://github.com/KusionStack/KCLVM/blob/fc853853415c5458db3d58d40857f576ff84d2ab/kclvm/runtime/src/api/utils.rs#L15-L22>

<https://github.com/KusionStack/KCLVM/blob/fc853853415c5458db3d58d40857f576ff84d2ab/kclvm/runtime/src/api/utils.rs#L24-L32>

<https://github.com/KusionStack/KCLVM/blob/fc853853415c5458db3d58d40857f576ff84d2ab/kclvm/runtime/src/api/utils.rs#L34-L44>

<https://github.com/KusionStack/KCLVM/blob/fc853853415c5458db3d58d40857f576ff84d2ab/kclvm/runtime/src/api/utils.rs#L46-L50>

<https://github.com/KusionStack/KCLVM/blob/fc853853415c5458db3d58d40857f576ff84d2ab/kclvm/runtime/src/api/utils.rs#L52-L57>

<https://github.com/KusionStack/KCLVM/blob/fc853853415c5458db3d58d40857f576ff84d2ab/kclvm/runtime/src/api/utils.rs#L59-L75>

<https://github.com/KusionStack/KCLVM/blob/6f9f2c779e273e85a9b760ce7861f58d258789d7/kclvm/runtime/src/api/buf.rs#L52-L62>

There may be more incorrect unsafe usages.

**Comment by Peefy** [comment]
Thank you very much for the issue, we will rewrite the entire runtime to make the program more soundness. Now, I've marked the issue with `help wanted`, you are welcome to get involved.

> https://github.com/KusionStack/KCLVM/blob/fc853853415c5458db3d58d40857f576ff84d2ab/kclvm/runtime/src/api/utils.rs#L15-L22
> 
> https://github.com/KusionStack/KCLVM/blob/fc853853415c5458db3d58d40857f576ff84d2ab/kclvm/runtime/src/api/utils.rs#L24-L32
> 
> https://github.com/KusionStack/KCLVM/blob/fc853853415c5458db3d58d40857f576ff84d2ab/kclvm/runtime/src/api/utils.rs#L34-L44
> 
> https://github.com/KusionStack/KCLVM/blob/fc853853415c5458db3d58d40857f576ff84d2ab/kclvm/runtime/src/api/utils.rs#L46-L50
> 
> https://github.com/KusionStack/KCLVM/blob/fc853853415c5458db3d58d40857f576ff84d2ab/kclvm/runtime/src/api/utils.rs#L52-L57
> 
> https://github.com/KusionStack/KCLVM/blob/fc853853415c5458db3d58d40857f576ff84d2ab/kclvm/runtime/src/api/utils.rs#L59-L75
> 
> https://github.com/KusionStack/KCLVM/blob/6f9f2c779e273e85a9b760ce7861f58d258789d7/kclvm/runtime/src/api/buf.rs#L52-L62
> 
> There may be more incorrect unsafe usages.

Thank you very much for the issue, we will rewrite the entire runtime to make the program more soundness. Now, I've marked the issue with `help wanted`, you are welcome to get involved.

**Comment by Peefy** [comment]
Associated with #191
