### ISSUE TITLE
The attribute operators `:` and `=` need to have a unified, simple and clear form that is easier for users to understand and use.

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl#200]
### Background

In the configuration scenario, there are often problems of configuration data inheritance, overwriting, and merging, such as the classic three-way merge problem. Some parameters in different environments in multiple environments expect to inherit the configuration of the base, and some expect to override the configuration of the base.

### Goals

* Eliminate users' doubts about using styles for different attribute operators (Should I use ':' or '=' to gracefully solve the configuration merge problem in my scenario
* Use the most common symbols to meet the most basic functions (configure merge override scenarios). For more scenarios, use more prominent extension symbols.
* Each operator is only responsible for the function of a single atom and can be combined.

### Problems

Different attribute operators are supported in KCL to express configuration coverage and merging. At the language level, two attribute operators, `:` and `=`, are provided to express merge and coverage respectively. Although this provides the flexibility of configuration merging, there are some problems:
* There is no limit to the number of configuration merges and the configured k-v-o entry consisting of key, value and the attribute operator is a runtime value, which makes users unclear about the path of their own configuration merges (improved by enhancing error messages and displaying merge tracing #193).
* The writing style of attribute operators may be inconsistent and Inconspicuous  (whether to use a more conspicuous symbol).

#### Example 1

KCL code (main.k)

```python
config1 =  {image = "xx", env = []} | {image = "override_image", env += []}
config2 =  {image: "xx", env: []} | {image = "override_image", env += []}
```

The output YAML (kcl main.k)

```yaml
config1:
  image: override_image
  env:
  - ENV
config2:
  image: override_image
  env:
  - ENV
```

The writing methods of config1 and config2 are equivalent, and their results are the same. Users can write both ':' and '='

#### Example 2

For the basic configuration and environment configuration, if the operator is used incorrectly, configuration conflicts may occur.

* base.k

```
app: App {
      image: "v1"
      labels: {
        k1 = "v1"
        k2 = "v2"
     }
    envs = [
            {name = "ENV1", value = "ENV2"}
    ]
}
```

* prod.k

```
app: App {
     image: "v2" # Error:value confict, using `=` override operator
      labels: {  # Use `:` to merge, use `=` to override
        k3 = "v3"
     }
    envs += [  # Use `+=` to add a env.
            {name = "ENV2", value = "ENV2"}
    ]
}
```

#### Example 3

```
input = {
    Deployment = [{}, {}]  # Omit the deplyment attributes
}

newResult = input | {
    Deployment: [
        {
            # Delete a label
            spec.template.metadata.annotations: {
                "pod.beta1.sigma.ali/hostname-template-sequence" = Undefined
            }

            # Add some labels
            if not data.keepHostname:
                metadata.annotations: {
                    "mock/pod-group" = "app"
                    "mock/hostname-template" = 'hostnameTemplate'
                    "mock/fqdn-template" = '_hostnameTemplate._idcDnsDomain'
                }

            # Add envs into all containers.
            spec.template.spec.containers: [
                {
                    env += [{name = "ENV1", value = "v1"}, {name = "ENV2", value = "v2"}] 
                } for c in deploy.spec.template.spec.containers
            ]
        } for deploy in input["Deployment"]
    ]
}

```

### Analysis

A direct cause of the current situation is that the user cannot immediately determine that one is an idempotent merge function and the other is overwrite function through the symbols ':' and '='. In many languages, the setting of ':' and '=' is':=', which represents the semantics of assignment, such as the following go code (`=` used in normal assign statements and `:` used in struct initialize expressions):

```go
package main

import "fmt"

type Person struct {
	name string
}

func main() {
	name := "Alice"
	name = "Bob"
	p := Person{name: name}
	fmt.Println(p)
}
```

Thus, if merging is regarded as an advanced use of overriding attributes, perhaps the forms `+:` and `:` like jsonnet are more acceptable. However, it does not solve the problem of unlimited merging and coverage. Of course, providing the traceback of merging or limiting the number of parameters can alleviate this problem to some extent, but it does not solve this problem from the language level.

#### Design I

It is specified that the best operator for KCL is `:` operator, | When combining two configurations, the Python dict Merge specification is used by default). However, the type of the original attribute cannot be changed during the merge process, so we will modify this process slightly:

`|:` indicates the dict merge patch and list merge patch like origin attr op `:`
`+:` indicates the list append op like origin the attribute op attr op `+=`
`!:` Indicates that the configuration will perform a merge conflict check.

Because KCL is not a jsonlike language, we use `+=` and `|=`for top level variables.

```python
# Literal

a = {a: 1} | {a: 2} # {"a": 2}
b = {a: 1} | {b: 2}  # {"a": 1, "b": 2}

# Dict

c = {a: {a: 1, b: 2}} | {a: {c: 3}} # {"a": {"c": 1}} The same key will be overwritten directly. If you want to merge, you can use "|:"
d = {a: {a: 1, b: 2}} | {a |: {c: 3}} # {"a": {"a": 1, "b": 2, "c": 3}}

# List

e = {a: [{a: 1}]} | {a: [{b: 2}]} # {"a": [{"b": 2}]}
f = {a: [{a: 1}]} | {a+: [{b: 2}]} # {"a": [{"a": 1}, {"b": 2}]}
g = {a: [{a: 1}]} | {a|: [{b: 2}]} # {"a": [{"a": 1, 'b": 2}]}
```

#### Design II

Expand immutable semantics for attribute operators in KCL:
* Properties declared with the=operator are immutable.
* Attributes declared using the: and+=operators are mutable.

```python
config1 = {a = 1} | {a = 2} # Error: `=` denotes that `a` is immutable.
config2 = {a: 1} | {a = 2}  # Ok: `:` denotes that `a` is mutable
```

### Reference

* KCL Config Operation: https://kusionstack.io/zh-CN/docs/reference/lang/lang/tour/#%E9%85%8D%E7%BD%AE%E6%93%8D%E4%BD%9C
* Jsonnet Nested Field Inheritance: https://jsonnet.org/ref/language.html `+:` and `:`
* The Logic of CUE: https://cuelang.org/docs/concepts/logic/
* Ksonnet: https://github.com/ksonnet/ksonnet
* StackOverflow Question [where to place cross-environment Terraform configs?](https://stackoverflow.com/questions/73489600/terragrunt-where-to-place-cross-environment-terraform-configs)
* JSON Merge Patch RFC: https://www.rfc-editor.org/rfc/rfc7386
* JSON Patch: https://jsonpatch.com/
* JSON Merger:https://pythonhosted.org/json-merger/_modules/json_merger/merger.html
* Acorn CUE Merge Function: https://docs.acorn.io/reference/functions#merge
* Python. PEP 584: https://peps.python.org/pep-0584/

**Comment by Peefy** [comment]
Base {image, env} prod image + 加一个环境

**Comment by chai2010** [comment]
```
{image = "xx", env = []} | builtin.Object {
    set: {
        image = "override_image"
    },
    append: {
        env: []
    }
}
```

**Comment by He1pa** [comment]
```
A = {
  image = "xx"
  env = []
}
B = {
  @overwrite
  image = "override_image"
  @append
  env = []
}
A|B
```

**Comment by Peefy** [comment]
In addition, CUE can complete up to two layers of data inheritance through *default_value, and can write multi-environment configurations to a certain extent, but it seems that it cannot cover the problems and scenarios that KCL needs to solve. Ref: https://cuetorials.com/deep-dives/attributes/#cues-attributes

**Comment by Peefy** [comment]
显式写出 keyword action.

**Comment by NeverRaR** [comment]
{
     config1 =  {
         image : "xx", 
         env : []
    } | 
    {
        image : "override_image", 
        env :<append> [ ]
    }
}

**Comment by zong-zhe** [comment]
A = {
  image = "xx"
  env = []
}
B = {
  image = "override_image"
  env = []
}

B.override(A)  
or  
B override A

**Comment by He1pa** [comment]
![image](https://user-images.githubusercontent.com/56333845/201305979-22500f0d-2aaa-416f-92c6-6b69a3bb56f3.png)
