### ISSUE TITLE
KCL-Vet should tell user the error line in json/yaml file.

### ISSUE THREAD

**Issue by zong-zhe** [kcl-lang/kcl#253]
## Feature Request

**Is your feature request related to a problem? Please describe:**

KCL-Vet should tell user the error line in json/yaml file.
At present, KCL-Vet can only tell the user what is wrong with the KCL constructed by KCL-Vet.

**Describe the feature you'd like:**

The output error message indicates which line of json/yaml is wrong.

**Describe alternatives you've considered:**

None

**Teachability, Documentation, Adoption, Migration Strategy:**

None

**Comment by Peefy** [comment]
Closed by #944 and #949
