### ISSUE TITLE
Remote imports or other means to pull external modules?

### ISSUE THREAD

**Issue by christianknoepfle** [kcl-lang/kcl#437]
## General Question
Currently we are using dhall for our configuration. One of the nice features are remote imports. Our schema definitions (i.e. the definition of which fields are part of a type) are located on a web server. When a user writes his configuration he just imports the (latest) schema definition and starts writing his config. There is no need to install something or keep it up to date.

Quick example:
````
-- Import definitions and then we can use the FileFormat definition
let Metadata =https://somehost.de/data_class_registry/latest/package.dhall
let format = Metadata.FileFormat.Csv { encoding = "UTF-8", header = True, quote = "", separator = ";" }
...
````

In the docs I found infos on imports but it seems that the packages/modules must be located on my local drive. There is no mentioning of a remote import.

This leads to the following questions:
* How is the intended way in KCL to deal with such scenarios? 
* Is there some update mechanism to install such schema definitions automatically (similar to some kind of a make/build tool that pulls dependencies to my local drive)?

Thanks a lot and best regards, 

Christian

**Comment by Peefy** [comment]
Thank you for your question. In March 2023, we are designing and developing a package management tool KPM (KCL Package Manager), which is expected to support the git repo, restful URL, and OCI Registry. For more details, please refer to:

+ #338
+ #339

If you have additional scenario requirements and pain points, please let us know, thank you!

**Comment by christianknoepfle** [comment]
Thanks for your quick response.  One thing that would be important is to provide basic auth (or some way to add a  customized header) for downloading a module/ package. We are storing our artefacts in jfrog artifactory and need authenticate in order to pull the artifact.

Thanks a lot and best regards Christian

**Comment by Peefy** [comment]
> Thanks for your quick response. One thing that would be important is to provide basic auth (or some way to add a customized header) for downloading a module/ package. We are storing our artefacts in jfrog artifactory and need authenticate in order to pull the artifact.
> 
> Thanks a lot and best regards Christian

Thank you, we will give priority to this. cc @zong-zhe

**Comment by Peefy** [comment]
@christianknoepfle Hi, there. We have released a preview version of the KCL package management tool [kpm](https://github.com/KusionStack/kpm) and sincerely invite you to conduct an evaluation. The documents is [here](https://kcl-lang.io/docs/user_docs/guides/package-management/installation). Thank you.

**Comment by Peefy** [comment]
External modules can be viewed on the artifact hub or kcl-lang/modules repo using the `kcl mod` tool.
