### ISSUE TITLE
[Enhancement] Add Code and Documentation AI Assistants for KCL

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl#461]
## Enhancement

Add Code and Documentation AI Assistants for KCL

## Why

+ AI cannot replace what KCL compilers or Kusion engines do.
+ AI cannot replace the value of collaborative programming and scalability in KCL, but we can further improve the efficiency of individuals and organizations by using AI to share and reuse KCL knowledge as much as possible.
+ We cannot use the existing LLM to help write KCL code because they do not contain knowledge of KCL and require precise tuning using KCL data.

## Goals

+ We can use the vscode-kcl extension to ask any questions about kcl codes and documents (A dialog or copilot-like capability). For example, a dialog with the hint `enter the kcl promot`.

## Design

![image](https://user-images.githubusercontent.com/22744597/234160172-dd168193-b87e-4003-87d9-b8fc366ca038.png)

#### Chat

```http
POST /v1/chat/completions
req body: { message: Prompt }
res body: { completions: Completion[]}
```

```typescript
export interface Prompt {
  input: string;
  model: string;
}

export interface Completion {
    prompt: string;
    competition: string;
}
```

#### KclService

https://kcl-lang.io/docs/reference/xlang-api/rest-api

### CLI

```shell
kcl-chat "How to install kcl"
```

### IDE Integration

+ VS Code: `cmd + shift + p` => `enter the kcl promot`

### Impl

Next.js + VSCode Plugin

## Reference

+ DocsGPT: https://github.com/arc53/DocsGPT
+ document.ai: https://github.com/GanymedeNil/document.ai
+ XLab Hypercrx
  + Plugin: https://chrome.google.com/webstore/detail/hypercrx/ijchfbpdgeljmhnhokmekkecpbdkgabc
  + Wechat: https://mp.weixin.qq.com/s/t2RmghxrGF2WLPW8NXwD_w
+ OpenAI Fine Tuning: https://platform.openai.com/docs/guides/fine-tuning
+ AIAC: https://github.com/gofireflyio/aiac
+ Kubectl-ai: https://github.com/sozercan/kubectl-ai
+ Langchain: https://github.com/hwchase17/langchain
+ Langchainjs: https://github.com/hwchase17/langchainjs
+ SQLChat: https://github.com/sqlchat/sqlchat
+ Databend: https://github.com/datafuselabs/databend
+ Askbend: https://github.com/datafuselabs/askbend
+ darklang: https://github.com/darklang/dark
+ cursor: https://www.cursor.so/
+ SQL Analyse GPT: https://www.patterns.app/blog/2023/01/18/crunchbot-sql-analyst-gpt

**Comment by He1pa** [comment]
Bito: https://plugins.jetbrains.com/plugin/18289-bito--gpt-4--chatgpt-to-write-code-explain-code-create-tests
