### ISSUE TITLE
[Feature] Kubectl KCL Plugin 

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl#520]
## Background

[KCL](https://github.com/KusionStack/KCLVM), which is specifically used for configuration writing and policy verification in cloud-native and Kubernetes scenarios. However, it is obviously not enough to use only one language for Kubernetes configuration management until we find Helmfile. 

One of the core issues to be addressed by KCL is to enhance configuration tools and provide declarative configuration verification and editing capabilities, serving to a certain extent as a glue layer for Configuration as Data (CaC) and Configuration as Data (CaD). Besides, KCL is a Python-like domain language with enhancement schema models and multiple override strategies for transforming configuration data without out-of-band access to the host filesystem and networking.

For example, the following image shows how KCL can be applied to cloud-native configuration and policy scenarios to generate, mutate, and validate Kubernetes manifests.

![image](https://user-images.githubusercontent.com/22744597/234481281-9b9141c5-a4cc-4ad3-b044-5905b92b9c24.png)

## Goals

TODO

## Implementation

+ kubectl-kcl: https://github.com/KusionStack/kubectl-kcl

## Reference

+ KPT: https://github.com/GoogleContainerTools/kpt
+ KPT KCL SDK Issue: https://github.com/GoogleContainerTools/kpt/issues/3671
+ KRM Function: https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/docs/api-conventions/functions-spec.md#krm-functions-specification
+ kpt-functions-catalog: https://github.com/GoogleContainerTools/kpt-functions-catalog
+ A KPT go function catalog: https://github.com/GoogleContainerTools/kpt-functions-catalog/tree/master/functions/go/set-namespace
+ Kustomize: https://github.com/kubernetes-sigs/kustomize
+ Build Custom Kustomize Plugin With Containerized KRM function: https://thirumurthi.hashnode.dev/build-custom-kustomize-plugin-with-containerized-krm-function
+ Helm: https://github.com/helm/helm
+ Helm Schema Generation Plugin: https://github.com/holgerjh/helm-schema
+ Helm Diff Plugin: https://github.com/databus23/helm-diff
+ Helm S3 Plugin: https://github.com/hypnoglow/helm-s3
+ Validating Helm Chart Values with JSON Schemas: https://www.arthurkoziel.com/validate-helm-chart-values-with-json-schemas/
+ Score Helm Chart: https://github.com/score-spec/score-helm-charts
+ Helmfile: https://github.com/helmfile/helmfile
+ Crossplane: https://github.com/crossplane/crossplane
+ keptn: https://github.com/keptn/keptn
+ Kubernetes Resource Model (KRM): https://github.com/kubernetes/design-proposals-archive/blob/main/architecture/resource-management.md
+ ArgoCD: https://github.com/argoproj/argo-cd
+ Terragrunt: https://terragrunt.gruntwork.io/
+ Grafana Helm charts: https://github.com/grafana/helm-charts
+ Grafana Jsonnet libs: https://github.com/grafana/jsonnet-libs
+ Grafana Tanka based on Jsonnet: https://github.com/grafana/tanka
+ Grafana Tanka Helm integration: https://tanka.dev/helm#helm-support
+ Prometheus Kubernetes Manifests based on Jsonnet: https://github.com/prometheus-operator/kube-prometheus
+ https://www.reddit.com/r/kubernetes/comments/118bmwu/helm_or_kustomize_for_my_situation/
+ https://www.reddit.com/r/kubernetes/comments/119jolm/separate_repository_for_helm_charts_vs_integrated/
+ https://www.reddit.com/r/kubernetes/comments/xx0e6h/why_we_use_cue_and_not_helm/
+ Why we use cue not helm: https://cloudplane.org/blog/why-cue
+ External Secret: https://external-secrets.io/v0.7.2/
+ Kubescape: https://github.com/kubescape/kubescape
+ https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/master/functions/go/starlark/starlark/config.go
+ OPA Libary: https://open-policy-agent.github.io/gatekeeper-library/website/

**Comment by Peefy** [comment]
@ekkoful Kind reminder ❤️: If you have good ideas and designs for KRM KCL and Kubectl KCL Plugin, you can directly add them to the issue and #479.

**Comment by ekkoful** [comment]
@Peefy ok. I will update the issue when I have the good designs . And you can assign the issue to me.

**Comment by ekkoful** [comment]
### Design
<img width="896" alt="image-20230503153654049" src="https://user-images.githubusercontent.com/42363586/235861094-58c6d9b6-9ff1-4c64-8f68-f9dbfac3d74c.png">

Sometimes if we want to modify a resource, may be we need `kubectl patch` or `kubectl edit`  to modify the resource.  But this way not a good way to modify large kubernetes resources.
Now we can use `Kubectl-kcl`  plugin to
- Apply kcl source code to modify large kubernetes resources and will apply to the kubrenetes runtime. You can focus on your logic to modify your kubernetes resource, don't maind for the way to modify large kubernetes resources batch.
- Run yaml file to generate kubernetes yaml file from kcl code
- ...
