### ISSUE TITLE
API: support generate KCL configuration and schema from json/yaml

### ISSUE THREAD

**Issue by amyXia1994** [kcl-lang/kcl#530]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

provide APIs to generate KCL configuration from json/yaml/...

from json/yaml/... data representation and the schema definition

```yaml
name: "demo"
mainContainer:
  name: "main"
  image: "image-ns:tag"
replicas: 1
```

```python
schema Server:
    name: str
    mainContainer: Container
    replicas: int = 1

schema Container:
    name: str
    image: str
```
to kcl configuration: (the variable name `appConfiguration` is passed from API args)
```python
appConfiguration: Server {
    name: "demo"
    mainContainer: {
        name: "main"
        image: "image-ns:tag"
    }
    # if the configuration value is exactly the same as the default value, the configuration could be omited
    # replicas: 1
}
```

**Describe alternatives you've considered:**

directly assign the json format data to the variable, then call the `KclvmService.FormatCode` API:

```python
appConfiguration: Server {
    "main": "demo",
    "mainContainer": {
        "name": "main",
        "image": "image-ns:tag"
    },
    "replicas": 1
}
```

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Peefy** [comment]
This is a great enhancement that requires unified consideration of other data (protobuf/openapi/yaml/json/teraform schema/...) integration interfaces in both the CLI and API interfaces, such as the **cue import tool**:

+ From data to KCL config
+ Infer data to KCL schema
+ Other schemas to KCL schemas
+ ...

Additionally, note that there are some incompatibilities between JSON and KCL Config in the alternative solutions, e.g., null/None, true/True, false/False

**Comment by prahaladramji** [comment]
I would also add another behaviour as a requirement which currently the cue import donest do.

Eg the provided json/yaml file ends up becoming non-mutable values in the generated config, for usecases where we want to override yamls from helmcharts or other sources, it would be nice to be able to mutate some of the values.

eg,
upsterem image url, would need to be able to mutate to something we want to change.

In the current Cue import behaviour this is not allowed, so one needs to modify the generate file which makes it hard to maintain. With jsonnet since it let's you mutate everything, the overrides and patches are defined sperately and the generated file can be regenerated safely.

**Comment by Peefy** [comment]
> I would also add another behaviour as a requirement which currently the cue import donest do.
> 
> Eg the provided json/yaml file ends up becoming non-mutable values in the generated config, for usecases where we want to override yamls from helmcharts or other sources, it would be nice to be able to mutate some of the values.
> 
> eg,
> upsterem image url, would need to be able to mutate to something we want to change.
> 
> In the current Cue import behaviour this is not allowed, so one needs to modify the generate file which makes it hard to maintain. With jsonnet since it let's you mutate everything, the overrides and patches are defined sperately and the generated file can be regenerated safely.

❤️ Thank you for your reply. I think I have understood your input and we will carefully consider and design for the data  migration and mutation.
