### ISSUE TITLE
[Enhancement] Add `-H/--show-hidden` flag to show hidden attributes e.g. `_hidden_attr`

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl#536]
## Enhancement

Add `-H/--show-hidden` flag to show hidden attributes e.g. `_hidden_attr`

## Example

A KCL file (main.k)

```python
a = 1
_b = 2
```

Run the command

```shell
$ kcl a.k
a: 1

$ kcl a.k -H
a: 1
_b: 2
```

**Comment by niconical** [comment]
There is a [test case](https://github.com/KusionStack/kcl/tree/main/test/grammar/scalar/number/number_1)
```shell
_a = 1
_a
```

The original output is

```shell
1
```

It's not clear to me, what is the expected output of this test case if the `-H/--show_hidden` parameter is used?

**Comment by Peefy** [comment]
> 有一个测试用例[kcl/test/grammar/scalar/number/number_1](https://github.com/KusionStack/kcl/tree/main/test/grammar/scalar/number/number_1)
> 
> ```shell
> _a = 1
> _a
> ```
> 
> 原始输出是
> 
> ```shell
> 1
> ```
> 
> 我不清楚，如果`-H/--show_hidden`使用参数，这个测试用例的预期输出是什么？我认为，不同的期望输出可能会影响最终实施的复杂性。

The `-H` flag indicates that non scalar attributes starting with an underscore can be output, such as a dictionary, which is different from outputting a scalar in a test case.

```python
_a = 1
```

The output is

```yaml
_a: 1
```

In this example, we expect the output to be `_a`. What its value is not important.
