### ISSUE TITLE
KCL language server high CPU usage

### ISSUE THREAD

**Issue by He1pa** [kcl-lang/kcl#547]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Typing following code in VSCode
```
a = True
if a:
    _abc = 1
else:
    _abc = 2
```

### 3. What did you see instead (Required)
![image](https://github.com/KusionStack/KCLVM/assets/56333845/0d6dbc59-007a-4e2f-b1e2-0d7d157d1435)

**Comment by Peefy** [comment]
There may be an endless loop trap of lexical syntax error recovery, which causes the CPU to be temporarily high.
