### ISSUE TITLE
`llvm-as` dependency in dev_docs

### ISSUE THREAD

**Issue by niconical** [kcl-lang/kcl#562]
I tried to execute `cd ./kclvm && make gen-runtime-api` on Ubuntu but got an error
```shell
...
make[1]: llvm-as: No such file or directory
```

I have installed dependencies according to the [Development Guide](https://github.com/KusionStack/kcl/blob/main/docs/dev_guide/2.quick_start.md#quick-start), but it seems that this command in docs `apt-get install -y clang-12 lld-12`  is not enough to install all dependencies of this project, such as `llvm-as`.

Finally I solved my problem through this link https://apt.llvm.org/

**Comment by Peefy** [comment]
> I tried to execute `cd ./kclvm && make gen-runtime-api` on Ubuntu but got an error
> 
> ```shell
> ...
> make[1]: llvm-as: No such file or directory
> ```
> 
> I have installed dependencies according to the [Development Guide](https://github.com/KusionStack/kcl/blob/main/docs/dev_guide/2.quick_start.md#quick-start), but it seems that this command in docs `apt-get install -y clang-12 lld-12` is not enough to install all dependencies of this project, such as `llvm-as`.
> 
> Finally I solved my problem through this link https://apt.llvm.org/

OK, for release and test, the llvm build deps is enough, may lost `llvm-as` for the runtime ABI generation. Ref: https://github.com/KusionStack/kcl/blob/main/.github/workflows/release.yaml

Are you willing to complete the llvm-as dependencies in the [document](https://github.com/KusionStack/kcl/blob/main/docs/dev_guide/2.quick_start.md) and [CI](https://github.com/KusionStack/kcl/blob/main/.github/workflows/release.yaml), based on your experience:)

**Comment by niconical** [comment]
> > I tried to execute `cd ./kclvm && make gen-runtime-api` on Ubuntu but got an error
> > ```shell
> > ...
> > make[1]: llvm-as: No such file or directory
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I have installed dependencies according to the [Development Guide](https://github.com/KusionStack/kcl/blob/main/docs/dev_guide/2.quick_start.md#quick-start), but it seems that this command in docs `apt-get install -y clang-12 lld-12` is not enough to install all dependencies of this project, such as `llvm-as`.
> > Finally I solved my problem through this link https://apt.llvm.org/
> 
> OK, for release and test, the llvm build deps is enough, may lost `llvm-as` for the runtime ABI generation. Ref: https://github.com/KusionStack/kcl/blob/main/.github/workflows/release.yaml
> 
> Are you willing to complete the llvm-as dependencies in the [document](https://github.com/KusionStack/kcl/blob/main/docs/dev_guide/2.quick_start.md) and [CI](https://github.com/KusionStack/kcl/blob/main/.github/workflows/release.yaml), based on your experience:)

I'll fix related Docs and CI in my free time.

**Comment by niconical** [comment]
I'll fix it within the next week.

**Comment by Peefy** [comment]
Have added the llvm-as tool in all docker images.
