### ISSUE TITLE
Evaluate Profile-Guided Optimization (PGO) and LLVM BOLT

### ISSUE THREAD

**Issue by zamazan4ik** [kcl-lang/kcl#647]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Not a feature. Just an idea of how to improve the performance of the KCL ecosystem. If it's a wrong issue type - would be nice if you fix it.

**Describe the feature you'd like:**
According to the [tests](https://github.com/zamazan4ik/awesome-pgo#compilers-and-interpreters), Profile-Guided Optimization (PGO) helps a lot with performance optimization, especially for compiler-like workloads (like Rustc, Clang, GCC and others). I think would be a good idea to try to apply PGO on KCL tooling. The tooling performance is important since it reduces CI costs and improves the local development experience (quicker write-compile-check feedback loops).

We need to evaluate PGO performance improvements for the KCL ecosystem. And if it improves things somehow, we have the following ways:

* Write a note in the documentation about PGO results with KCL compilers. So maintainers and end-users would know it and possibly consider using PGO for their own builds
* Optimize distributed by KCL [binaries](https://kcl-lang.io/docs/user_docs/getting-started/install) with PGO. It could be a bit trickier option since you need to prepare/collect somehow a "generic-enough" profile. Maybe the Rustc project experience would be valuable here.

For the Rust projects, I suggest starting with [cargo-pgo](https://github.com/Kobzol/cargo-pgo).

After PGO would be a nice idea to evaluate LLVM BOLT as well (e.g. Rustc compiler is already PGO+BOLT optimized on some platforms).

More materials about PGO (more showcases, possible caveats, other options like AutoFDO, etc) you can find [here](https://github.com/zamazan4ik/awesome-pgo#compilers-and-interpreters).

**Describe alternatives you've considered:**
Do nothing :)

**Teachability, Documentation, Adoption, Migration Strategy:**
Not sure what to write here. I think at least a page in the documentation about building the tooling itself with PGO is worth it.

**Comment by Peefy** [comment]
I think you are right. PGO has already made performance contributions in many compilers, and trying to use PGO in KCL is beneficial for the entire ecosystem. It is best to have corresponding documentation added to this. ❤

**Comment by Peefy** [comment]
As there have been no further updates on this issue for more than three months, I will close it to keep the issue list tidy.
