### ISSUE TITLE
Bug: the IDE failed to output the expected error.

### ISSUE THREAD

**Issue by zong-zhe** [kcl-lang/kcl#667]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

I have the kcl program as below:
```
The_first_kcl_program = 'Hello World!'

schema SchemaInMainK:
    msg: str

schema_in_main_k = SchemaInMainK(msg='I am the instance of SchemaInMainK')
```

### 2. What did you expect to see? (Required)

This is not a correct KCL program, the IDE should show me the error.

```
$ kcl main.k
error[E3M38]: EvaluationError
 --> /Users/main.k:6:1
  |
6 | schema_in_main_k = SchemaInMainK(msg='I am the instance of SchemaInMainK')
  |  attribute 'msg' of SchemaInMainK is required and can't be None or Undefined
  |

```

### 3. What did you see instead (Required)

The LSP is still work,but failed to output errors.
<img width="533" alt="截屏2023-08-17 18 13 37" src="https://github.com/kcl-lang/kcl/assets/68977949/e5ad7aca-66e7-4fa9-a32b-31d801109e9c">

### 4. What is your KCL components version? (Required)

I build the KCL from the branch main.

```
$ kcl --version
Version: 0.5.4-20ab3eb4b9179219d6837a57f5d35286
Platform: aarch64-apple-darwin
GitCommit: a15a3157608079eb93d2b95d4a1f809bbff5aa46
```
```

**Comment by He1pa** [comment]
KCL IDE only checks for syntax and semantic errors, not contains runtime errors
