### ISSUE TITLE
[Enhancement] ArtifactHub KCL Integration

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl#716]

**Comment by zong-zhe** [comment]
The integration request: https://github.com/artifacthub/hub/issues/3350
The discussion before: https://github.com/artifacthub/hub/discussions/3257

**Comment by Peefy** [comment]
We need to build a index git repo just like: https://github.com/keptn-contrib/artifacthub to help developers to build and publish a kcl package for the artifactHub KCL Integration? cc @zong-zhe

**Comment by zong-zhe** [comment]
# The Integration
AH ([artifacthub.io](http://artifacthub.io/)) obtains information display on the web UI about all packages through a [metadata file](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-pkg.yml)

Firstly, we would like to utilize AH as a marketplace for `KCL package`. We aim for KCL users to be able to discover or publish their packages through AH.

Therefore, there are some points that need attention.

- Users can use "kpm push" to publish KCL packages to AH, and they will be able to see detailed information about the KCL packages in AH.
- AH retrieves and displays detailed information about the package through its metadata.

Therefore, the things I need to do are as follows:
- Prepare a git repo [artifacthub](https://github.com/kcl-lang/artifacthub) to store all the metadata of KCL packages. The metadata should include a `README.md` file for displaying detailed information and an `artifacthub-pkg.yml` file for package metadata. 
- KPM should provide `kpm metadata`, to get the metadata of a particular package, which can be used as a source of data to generate `artifacthub-pkg.yml`.
- After being triggered, The  [artifacthub](https://github.com/kcl-lang/artifacthub)  CI calls `kpm metadata` to obtain the package metadata and generates `artifacthub-pkg.yml`.

<img width="748" alt="截屏2023-10-19 10 53 07" src="https://github.com/kcl-lang/kcl/assets/68977949/4a90386b-9655-435f-861e-ccc816b69fe6">

The above picture shows the workflow of presenting the contents of the KCL package on AH via KPM. 

- When KPM push the KCL package to OCI registry, it add the metadata of the KCL package to the OCI manifest configuration file.

- A new package pushed to the OCI registry will trigger the CI of the metadata repo [artifacthub](https://github.com/kcl-lang/artifacthub).

- The CI will generate the `artifacthub-pkg.yml` based on the metadata of the new KCL package.

- AH will poll the repository every half hour to display the contents of the repository on AH's WebUI.

# The next steps.

- [ ] The metadata of a kcl package. 
- https://github.com/kcl-lang/kpm/issues/199
- [ ] `kpm push` should add the metadata of the kcl package to the OCI manifest file. 
- https://github.com/kcl-lang/kpm/issues/201
- [ ] `kpm metadata` should show more detailed information abut a KCL package.  
- https://github.com/kcl-lang/kpm/issues/202
- [ ] The `artifacthub-pkg.yml` generator in [artifacthub](https://github.com/kcl-lang/artifacthub). 
- https://github.com/kcl-lang/artifacthub/issues/2

**Comment by zong-zhe** [comment]
# The demo show in staging (https://staging.artifacthub.io/)

https://staging.artifacthub.io/packages/search?kind=20
https://staging.artifacthub.io/docs/topics/repositories/kcl-packages/
