### ISSUE TITLE
[Enhancement][Design] improve performance of find refs 

### ISSUE THREAD

**Issue by amyXia1994** [kcl-lang/kcl#723]
The find refs performance is kind of slow.

## Goals of find refs tool

The find refs tool could be widely used. Here is an incomplete list of most common usages:

### Context of use

How `find references` is used by end users:
**From IDE**:
- Go to Reference: this is user input blocking
- Find all references: show all references in an async way
- Refactor: rename symbols/files, ... It is based on find refs
- Lint: detect unused symbols(variable/schema/…). It is based on find refs

**From CI Pipeline**:
The background is, for large-scale mono repo, Fine-grained unit testing is necessary to provide acceptable time cost on unit tests each time a code change is prompted.
- symbol-level dependent analysis tool to narrow down the scope that need test
- lint tools in CI pipeline

### IDE Support

todo, add the benchmark data

The most 2 time consuming hot spots are:

- time to read all the files and build the word index
- time to compile all the files that contain the name-matched symbols.

These could be solved in two aspects:
- Cache the word index: build the word index once (at the lsp initialize phase), and incrementally update it if the workspace content changes. 
- Incrementally display the ref items: based on the [partialResults progress support by LSP 3.17](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#partialResults), the analysis results could be displayed partially and incrementally. So the language server could analyze the refs results in batches and asynchronously.

![image](https://github.com/kcl-lang/kcl/assets/29722609/0af5bf2f-9ad3-45f8-a7f4-6f3609d1633d)

**Comment by He1pa** [comment]
Do we need to cache all vfs during initialization? It is necessary to consider the memory usage of all vfs caches of mono repo

**Comment by amyXia1994** [comment]
> Do we need to cache all vfs during initialization? It is necessary to consider the memory usage of all vfs caches of mono repo

Do you mean "the cached vfs" in the initialize phase?
![image](https://github.com/kcl-lang/kcl/assets/29722609/8c5f9129-a4f2-4c1f-bda4-e6a43de275f2)

There may be ambiguity of my mentioning "the cached vfs" here, what I meant to express is to initialize an empty vfs on lang-server initialize phase, not to read and cache all the workspace files. The vfs caching strategy stays unchanged in this design.

**Comment by amyXia1994** [comment]
Updated:
