### ISSUE TITLE
support global import packages

### ISSUE THREAD

**Issue by zwpaper** [kcl-lang/kcl#729]
## Feature Request

**Is your feature request related to a problem? Please describe:**

kcl has kpm which can be used to create a project and download packages like k8s, and then one can use the k8s models under the project.

but most of the use of k8s yaml would be to write a single file directly, it's dummy to create a project for all yaml or create a project each time when needed.

**Describe the feature you'd like:**

import packages like k8s directly without creating a project.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Peefy** [comment]
@zwpaper Hi there, Thank you for your request. ❤️

Firstly, it should be noted that your proposal is very good. We are currently carrying out corresponding work and have done some preliminary work (following are relevant discussions, issues, and PRs). The data and schema of other ecosystems, as well as the KCL configuration and schema conversion, are very important, considering the large number of YAML, Kustomize, and Helm configurations in the K8s ecosystem.

+ https://github.com/kcl-lang/kcl/issues/530
+ https://github.com/kcl-lang/kcl-go/pull/150
+ https://github.com/orgs/kcl-lang/discussions/651

We expect to provide a complete kpm import tool in KCL v0.7. x for unified import of other ecosystems, including data and schema, PRs welcome! ❤️

**Comment by Peefy** [comment]
> import packages like k8s directly without creating a project.

Just like this without the `kcl.mod` file and deps?:

```python
import "k8s:1.27" as k8s
```

**Comment by zwpaper** [comment]
> > import packages like k8s directly without creating a project.
> 
> 
> 
> Just like this without the `kcl.mod` file and deps?:
> 
> 
> 
> ```python
> 
> import "k8s:1.27" as k8s
> 
> ```
> 
> 

yes, that would be great to me

**Comment by Peefy** [comment]
Closed by https://github.com/kcl-lang/kpm/pull/215.

We can put the k8s module or create a symlink to the path `./.kcl/kpm/k8s`, then we can import the `k8s` module without creating a kcl project.
