### ISSUE TITLE
Discrepancies between kcl and kpm

### ISSUE THREAD

**Issue by steeling** [kcl-lang/kcl#734]
kcl has the benefit of being able to run against single files. So if I have an app structure like something described in https://github.com/kcl-lang/konfig/tree/main/appops/guestbook, kcl is great. kpm however, cannot specify individual files/directories, and in fact only looks in the current directory (as far as I understand).

KCL however does not allow referencing external packages, like the example on the [kpm page](https://github.com/kcl-lang/kpm)

```
# Import and use the contents of the external dependency 'k8s'.
import k8s.api.core.v1 as k8core

k8core.Pod {
    metadata.name = "web-app"
    spec.containers = [{
        name = "main-container"
        image = "nginx"
        ports = [{containerPort = 80}]
    }]
}
```

kcl cannot interpret this and returns an error.

My question is, am I understanding this correctly? Are there better workarounds here? If not, is there any goal of aligning these?

**Comment by Peefy** [comment]
> My question is, am I understanding this correctly? Are there better workarounds here? If not, is there any goal of aligning these?

In terms of functionality, kpm cli is a superset of kcl cli (kpm uses the API of kcl to import external packages and adds OCI related features. The kcl `-E` flag is used to add external packages), and we are working hard to achieve complete all functions using only kpm cli. In addition, you can use the kpm run command line to complete the code run in Konfig.

```bash
kpm run -Y ./appops/guestbook/dev/kcl.yaml
```

**Comment by steeling** [comment]
Gotcha. As a commentary, I would prefer explicit and declarative inclusion of files for evaluation of imports, vs the implicit/imperative form of running kpm/kcl with multiple files.

For instance, in the example provided, ./appops/guestbook/dev/main.k requires ./appops/guestbook/base/base.k to override some values. This also makes ordering a bit awkward. 

Instead, I would expect:

```
guestbook_frontend = base.guestbookFrontend {
  // apply overrides
}
```

as a more explicit option. Anyways, just my 2 cents, not sure if this desirable or not for the project

**Comment by steeling** [comment]
Also is there any way to get kpm functionality from the `kcl-go` sdk?

**Comment by Peefy** [comment]
> Also is there any way to get kpm functionality from the `kcl-go` sdk?

U can use kpm APIs https://github.com/kcl-lang/kpm/tree/main/pkg/api

**Comment by Peefy** [comment]
> Are there any plans to allow `kpm run <files>` to achieve feature parity with `kcl`, and to avoid creating too many settings yaml files?

Yes, we did. U can just use the `kcl.mod` file like the example: https://github.com/kcl-lang/kpm/blob/26ede830cdbd202e98f7df32a455c4232c251132/pkg/api/test_data/test_work_dir/dev/kcl.mod#L5

The document is here: https://github.com/kcl-lang/kpm/blob/26ede830cdbd202e98f7df32a455c4232c251132/docs/kcl_mod.md?plain=1#L16

**Comment by steeling** [comment]
> U can use kpm APIs https://github.com/kcl-lang/kpm/tree/main/pkg/api

The KPM API's are imported as package `kcl-lang.io/kpm`, which sits behind a mirror https://kcl-lang.io/kpm/, that doesn't allow importing. So it's not currently possible to import unfortunately these.

> Yes, we did. U can just use the kcl.mod file like the example

I can explain our use case a bit more. Let's say we have 100 clusters we want to describe, with 100 different `main.k` files. It would be nice to just have to create the `main.k` file, and not have to worry about setting all of the `settings.yaml`, or properly editing `kcl.mod` files to include different permutations of entries.

I would like to just pass in the files via the CLI. I could wrap this myself if `kpm`'s API were made to be import-able :)

**Comment by Peefy** [comment]
> The KPM API's are imported as package kcl-lang.io/kpm, which sits behind a mirror https://kcl-lang.io/kpm/, that doesn't allow importing. So it's not currently possible to import unfortunately these.

Hi @steeling. Thank you for your explanation. What do you mean is that you cannot use the API of kpm by importing it? For example, the warehouse below introduces the dependency of kpm through the **go.mod** and uses it in the code.

+ go.mod: https://github.com/kcl-lang/krm-kcl/blob/main/go.mod#L13
+ code: https://github.com/kcl-lang/krm-kcl/blob/main/pkg/source/oci.go#L10 or https://github.com/KusionStack/kusion/blob/main/pkg/generator/kcl/kcl_generator.go#L76

**Comment by steeling** [comment]
ah my mistake, I was trying to import packages from main that are not in v0.3.6
