### ISSUE TITLE
[Bugfix] Language Server sometimes crashes and won't restart automatically

### ISSUE THREAD

**Issue by amyXia1994** [kcl-lang/kcl#760]
## Bug Report

Language Server sometimes crashes and must be restarted manually to continue use. 

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

write KCL code, edit, save file, then close file

and here's the error in output:

```
[Info  - 10:48:41] on notification Notification { method: "textDocument/didSave", params: Object {"textDocument": Object {"uri": String("file:///Users/amy/demo/pkg/vars.k")}} }
[Info  - 10:48:41] on did save file: AbsPathBuf("/Users/amy/demo/pkg/vars.k")
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /Users/amy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ra_ap_vfs-notify-0.0.149/src/lib.rs:49:53
[Info  - 10:48:42] on notification Notification { method: "textDocument/didClose", params: Object {"textDocument": Object {"uri": String("file:///Users/amy/demo/kk/b/a/c.k")}} }
[Error - 10:48:42] The kcl language server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

### 3. What did you see instead (Required)

![lQLPJwKtm1SajUTNAQrNA46wUbG7DsOc1rgFG1pjOAbFAA_910_266](https://github.com/kcl-lang/kcl/assets/29722609/4680a7df-3725-40f8-aaa8-f76a0bce3e77)

### 4. What is your KCL components version? (Required)
```
kcl-language-server version
Version: 0.6.0-20ab3eb4b9179219d6837a57f5d35286
Platform: aarch64-apple-darwin
GitCommit: 93eb9d7d2ecd084adbd064d4a0bce8901344addc
```

**Comment by amyXia1994** [comment]
https://docs.rs/crate/ra_ap_vfs-notify/0.0.178/source/src/lib.rs

**Comment by He1pa** [comment]
https://github.com/rust-lang/rust-analyzer/issues/3715

**Comment by He1pa** [comment]
similar bug: https://github.com/rust-lang/rust-analyzer/issues/14539

**Comment by He1pa** [comment]
![image](https://github.com/kcl-lang/kcl/assets/56333845/0e4e247d-c95f-4175-8bed-eee071d459bf)

**Comment by He1pa** [comment]
ref: https://github.com/rust-lang/rust-analyzer/blob/d6afb4fa239fe7b5b34e5cefa9e58148fdff65b8/crates/rust-analyzer/src/global_state.rs
