### ISSUE TITLE
[Design][Track] The Overall KCL Tools User Experience Workflow and Enhancement

### ISSUE THREAD

**Issue by amyXia1994** [kcl-lang/kcl#767]
# KCL Tools Workflow

KCL Tools accelerates the lifecycle of the application development and deployment with application modeling. Here are core workflows on both model defining and application configuring.

### Platform engineer: model create/modify and deliver

Configuration modeling can be broken up into 3 phases, and for platform engineers that manage the models, we break down the steps and integrate the workflow into IDE and tools:
- model creation/modification
- model validation
- model publishing/releasing

![modeling drawio](https://github.com/kcl-lang/kcl/assets/29722609/91d8caad-0ea4-4725-bb70-e43fa2ba03a4)

#### model Design
- import/migrating models from API/other languages
- model design

#### model Test
- write unit test
- model Test Continuous Integration
- local validation

#### model Release
- incremental validation
- documentation Releasing
- publish to the registry

#### model Deprecation
- mark as deprecating
- update dependencies
- remove the model

![tools-workflow drawio](https://github.com/kcl-lang/kcl/assets/29722609/f3a0aafa-c227-4ca6-9e76-81c01343553a)

### Application Developer/SRE: Application configuration and shipping

**Application configuration and shipping** can be broken up into 4 phases for Application Developers/SREs that the applications:
- config creation/modification
- config validation
- config publishing
- config deploy and monitoring

![configuring_workflow](https://github.com/kcl-lang/kcl/assets/29722609/c9b9fa4a-4703-4112-9fe6-3c73883b18fa)

#### App Configuration Modification
- init the app configuration
- modify the configuration(manually or automatically)

#### App Configuration Test and Validation
- static validation:
  - diagostic and compile
  - policy
- e2e validation

#### App Configuration Publish
- package config
- upload, distribute config

#### App Configuration Deploy, Monitoring
- store versioned config
- apply config
- application monitoring
- [optional] rollback to previous stable release

![config_tools drawio](https://github.com/kcl-lang/kcl/assets/29722609/94ac1387-d658-44b7-bef3-9a59e268b104)

**Comment by zong-zhe** [comment]
#### Here are some more detailed workflow, designed to enhance the tool chain to help user to use third-party packages in KCL.

- When the IDE opens the KCL package, It automatically scans and downloads the existing dependencies in `kcl.mod` and update `kcl.mod.lock`.
- - This depends on https://github.com/kcl-lang/kpm/issues/200

- When the user edits the `kcl.mod` file, automatically updates local dependencies and updates `kcl.mod.lock`.
- - This depends on https://github.com/kcl-lang/kpm/issues/200

- When a ‘module not found’ error occurs, the IDE shows the command ‘kpm add’ or provides a guide link for AH in ‘quick fix’ or other way.
- When a ‘module not found’ error occurs, kpm show the diagnostic includes suggestions for `kpm add` or the guide link to AH.

**Comment by Peefy** [comment]
1. What is the overall goal and pace of production and research, such as to what extent the IDE and tools will be achieved by 2023?
2. One is what capabilities we already have, which ones require experience optimization, and which ones require a period of investment in new development?

**Comment by Peefy** [comment]
Many models are imported from other ecosystems, such as Kubernetes, Terraform, Cloudformation, etc., and such activities need to be considered.
