### ISSUE TITLE
KCL doesn't lazy eval dictionary lookups

### ISSUE THREAD

**Issue by steeling** [kcl-lang/kcl#774]
### 1. Minimal reproduce step (Required)

```
schema MySubSchema:
  a: int
  b: str
  c: {str:str}
  d: str = c[b]  // comment this line out to have this succeed.


schema MyTestSchema:
  field1?: [MySubSchema] = [
    {a: 1},
  ]


instance = MyTestSchema{
  field1 =  None
}
```
This results in an error.

### 2. What did you expect to see? (Required)
I expect no errors, since I override field1 to None in `instance`, the templated `field` should never be evaluated. 

If I modify the example slightly, such that I comment out the highlighted line above, it passes, even though there are omitted required fields.

### 3. What did you see instead (Required)

```
5 |   d: str = c[b]
  |  'UndefinedType' object is not subscriptable with 'UndefinedType'
```

### 4. What is your KCL components version? (Required)

kpm 0.3.6

**Comment by Peefy** [comment]
@steeling Good Catch! 👍 Thank you for your feedback and we will consider optimizing the lazy eval process and provide it in the next version.
