### ISSUE TITLE
[Bug] KCL doesn't handle imports and lambdas corrrectly

### ISSUE THREAD

**Issue by steeling** [kcl-lang/kcl#782]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

This is true for both kcl and kpm:

Have 1 package import a schema from another package. It can be a local package, or a remote dep, the issue occurs for both.

```
import k8s.api.core.v1 as corev1

identity = lambda res: corev1.Container {
  res
}
```

The above compiles with no issue. However, if we try to modify `res`, we get an error:

```
import k8s.api.core.v1 as corev1

identity = lambda res: corev1.Container {
  res {
    name = "hello" // modifications are not allowed for some reason
  }
}
```

The error we see is: `name '@k8s.api.core.v1' is not defined`

We can mimic the same with kcl, and a schema defined in another package like `mypackage.MySchema`

If I bring `MySchema` into the local package, it works fine.

### 2. What did you expect to see? (Required)

No errors

### 4. What is your KCL components version? (Required)

kpm 0.3.6

```
kcl -v
Version: 0.5.6-20ab3eb4b9179219d6837a57f5d35286
Platform: x86_64-apple-darwin
GitCommit: ae8a89eb0bc597d3cccd1a8724d33fa0bde06e30
```

**Comment by Peefy** [comment]
Hello @steeling, you can use the code as following and upgrade the kcl version to 0.6.0, we will improve the error message

```python
import k8s.api.core.v1 as corev1

identity = lambda res: corev1.Container {
  res | { # Use the union operator `||`
    name = "hello" # modifications are not allowed for some reason
  }
}
```

**Comment by steeling** [comment]
I'm then left with the issue that I can't call lambda on a schema object itself:

```
schema MySchema:
  name: str

identity = lambda res: MySchema {
  res | {
    name = "hello"
  }
}

output = identity(MySchema)
```

Because `MySchema` is not instantiated I get the following error:

`unsupported operand type(s) for |: '"function"' and '"dict"'`

However, in my use case, I also can't pass in an instantiated object, because the required fields aren't lazily evaluated in my output. It seems they are evaluated prior to the call to the lambda. Is there a workaround for this?

**Comment by Peefy** [comment]
What you need is to patch some attributes in the lambda function and perform necessary required attribute checks? (This is because each KCL schema instance needs to meet the given constraints and types, and it does not perform all checks after the entire program ends) I guess this is an optional solution (Abstract a config for user and use it to init a real container):

```python
schema MyContainerConfig:
    name?: str

schema Container:
    name: str

identity = lambda config: MyContainerConfig -> Container {
  Container {
    name = config.name or "default-container-name"
  }
}

output = identity(MyContainerConfig {})
```

**Comment by steeling** [comment]
Just want to add that the initial fix would allow me to pass in a non instantiated schema. The below works:

```
schema Container:
    name: str

identity = lambda container: Container -> Container {
  container {
    name = "default-container-name"
  }
}

output = identity(Container)
```

That said, is there a way to access the container variable within the scope of the instantiated object? The below fails with error `name 'container' is not defined`

```
schema Container:
    name: str

identity = lambda container: Container -> Container {
  container {
    name = container.name or "default-container-name"
  }
}

output = identity(Container)
```

Similarly, I can't use `name = name or "default-container-name"`, which I would expect to work

**Comment by Peefy** [comment]
OK, I see. We will consider this. Thank you!

cc @zong-zhe
