### ISSUE TITLE
kcl hangs on syntax errror

### ISSUE THREAD

**Issue by steeling** [kcl-lang/kcl#783]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

I have what I assume to be a syntax error, that I didn't catch right away. KCL/kpm ends up hanging on this:

```
render = lambda app: { // the colon here causes an issue.
  [
    app.service,
    app.deployment,
  ]
}
```

where correct code is:

```
schema Application:
  ...
render = lambda app: Application {
  [
    app.service,
    app.deployment,
  ]
}
```

### 2. What did you expect to see? (Required)

Compile time error

### 3. What did you see instead (Required)

Runtime hangs indefinitely

### 4. What is your KCL components version? (Required)

kpm 0.3.6

**Comment by Peefy** [comment]
Hi @steeling, we have done this in #692. You can upgrade your kcl to the latest version (v0.6.x)
