### ISSUE TITLE
Improved error messages

### ISSUE THREAD

**Issue by steeling** [kcl-lang/kcl#784]
## Feature Request

**Is your feature request related to a problem? Please describe:**
1. Stack traces in error messages. When I get it an error, it would help with debugging to print the stack trace of references, instead of just the one line error. 

2. Additional debugging tools, like adding a flag to print all contents (including contents that contains errors), ie:

```
result = {
   field1: `error: invalid reference: 'a' does not exist`
   field2: 10
}
```

**Comment by Peefy** [comment]
Hi @steeling . Thank you for your feedback.
1. You can use the cli flag to show the stack trace, ref: https://kcl-lang.io/blog/2022-kcl-0.5.0-release-blog/#runtime-backtrace-output
2. We have the debug tool issue to track this: #188 and I will close this issue to avoid repetition. If needed, you can add more detailed information there.

**Comment by steeling** [comment]
thanks for the tip, and thanks for all your quick replies and help @Peefy!
