### ISSUE TITLE
[Bug] Multi-level inheritance is not working

### ISSUE THREAD

**Issue by steeling** [kcl-lang/kcl#785]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

The below returns an error, but works when the last commented line is uncommented

```
schema Metadata:
  environment: str
  region: str
  name: str

schema MySchema1:
  metadata: Metadata

schema MySchema2(MySchema1):
  metadata.environment = "dev"

schema MySchema3(MySchema2):
  metadata.region = "us-east-1"

output = MySchema3 {
  metadata.name = "hello"
  # uncomment the next line to make this work, but I shouldn't have to, as it should be inherited.
  # metadata.environment = "dev"
}
```

### 2. What did you expect to see? (Required)

I expected the output 

```
output:
  metadata:
    environment: dev
    region: us-east-1
    name: hello
```

### 3. What did you see instead (Required)

` attribute 'environment' of Metadata is required and can't be None or Undefined`

### 4. What is your KCL components version? (Required)

kpm 0.3.6

**Comment by Peefy** [comment]
We have fix it in #787, it will be released in version 0.6.1 of kcl. You can refer to it and indicate if there are any further issues. Thank you! ❤️
