### ISSUE TITLE
[Bug][LSP]AnalysisDatabase not found error after rename file

### ISSUE THREAD

**Issue by amyXia1994** [kcl-lang/kcl#795]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create file a.k
rename to aa.k

### 3. What did you see instead (Required)

![lQLPJwl2vf3Ja2TNAYLNCvKwBHV6_uT30xUFI4afWECsAA_2802_386](https://github.com/kcl-lang/kcl/assets/29722609/d8a1d7fc-ea3b-4265-99fb-d9a9f8a2f256)

**Comment by He1pa** [comment]
In fact, it is not the error that occurs when renaming the file name, but the file extension. The client mistakenly sent a request for a KCL file, but the target file was not KCL (`.kcl` instead of `.k`).

 reproduce step should be rename file to a.kcl
