### ISSUE TITLE
[bug] the attribute type is always `any` in generated doc when import remote kpm packages

### ISSUE THREAD

**Issue by amyXia1994** [kcl-lang/kcl#823]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. `kcl import -m crd`
2. `kcl doc generate`

the crd source code uses remote kpm package `k8s` as dependency
![source_code](https://github.com/kcl-lang/kcl/assets/29722609/08384101-7530-44e0-aee8-8468664fa383)
![doc](https://github.com/kcl-lang/kcl/assets/29722609/5651fb33-3aff-4dc4-8b81-a49aa8e85cf1)
![remote_dependency](https://github.com/kcl-lang/kcl/assets/29722609/0210604d-ece4-4cab-a027-5dd7a6d87e2c)

### 2. What did you expect to see? (Required)
the metadata type in generated doc should be `ObjectMeta`

### 3. What did you see instead (Required)
`any`

**Comment by amyXia1994** [comment]
the problem cannot be reproduced by `kcl import -m crd <crd path> and `kcl doc generate <kcl file>`

did you init a kpm package based on the crd kcl files and add k8s as dependency? please provide complete information

**Comment by amyXia1994** [comment]
I tried to reproduce it, but:

1. `kcl import -m crd ~/krm-crd.yaml -o ~/`
2. `cd ~/ && kpm init kcl-run`
3. `cd ~/kcl-run && kpm add k8s:1.28`
4. `cp ~/models/krm_kcl_dev_v1alpha1_k_c_l_run.k ~/kcl-run/`
5. `kcl doc generate ~/kcl-run`

and the error is:

![image](https://github.com/kcl-lang/kcl/assets/29722609/169931cd-1b8d-4bbe-b71b-60b49a641db7)

**Comment by Peefy** [comment]
> I tried to reproduce it, but:
> 
> 1. `kcl import -m crd ~/krm-crd.yaml -o ~/`
> 2. `cd ~/ && kpm init kcl-run`
> 3. `cd ~/kcl-run && kpm add k8s:1.28`
> 4. `cp ~/models/krm_kcl_dev_v1alpha1_k_c_l_run.k ~/kcl-run/`
> 5. `kcl doc generate ~/kcl-run`
> 
> the doc generation is failed so I couldn't see the `any` type bug and the error is as following:
> 
> ![image](https://user-images.githubusercontent.com/29722609/282795127-169931cd-1b8d-4bbe-b71b-60b49a641db7.png)

cc @zong-zhe
