### ISSUE TITLE
Feature: the cache should be configurable

### ISSUE THREAD

**Issue by zong-zhe** [kcl-lang/kcl#835]
## Feature Request

**Is your feature request related to a problem? Please describe:**

In some locations where write permissions are lacking, compilation may fail due to the inability to write to the cache. Therefore, it's necessary to change the cache path.

Here is more detailed information https://github.com/orgs/kcl-lang/discussions/804.

**Describe the feature you'd like:**

Something can help me change the cache path.

For example by the env:

```
CACHE_PATH=/xxx/xx/xx
```

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by liangyuanpeng** [comment]
If you mark this issue as help want you probably don't want to assign self.
