### ISSUE TITLE
kusion compile error

### ISSUE THREAD

**Issue by ddh-open** [kcl-lang/kcl#846]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

kcl version 0.5.0-alpha.3
kusion compile 
<img width="1368" alt="image" src="https://github.com/kcl-lang/kcl/assets/98205714/d4cba78a-5a90-49a6-b4c0-4c8cff0b61a6">

**Comment by Peefy** [comment]
I noticed that the kcl version you provided is v0.5.0. Can you upgrade both kcl and kcl language server to the latest stable version (v0.6.0+).
