### ISSUE TITLE
校验器添加具体错误

### ISSUE THREAD

**Issue by XiaoK29** [kcl-lang/kcl#867]
## Feature Request

**Is your feature request related to a problem? Please describe:**

校验器只能检验文件合格性，无法精确到第几行错误

**Describe the feature you'd like:**

抛出文件第几行错误，以及具体错误，比如类型错误还是校验规则错误
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Peefy** [comment]
Hi @XiaoK29, thank you for your feedback. This is the relevant issue: #253 cc @zong-zhe

**Comment by XiaoK29** [comment]
> Hi @XiaoK29, thank you for your feedback. This is the relevant issue: #253 cc 您好，感谢您的反馈。这是相关问题：#253 cc@zong-zhe

好的

**Comment by Peefy** [comment]
@XiaoK29 PRs welcome. ❤️
