### ISSUE TITLE
[Bug]Error positions for undefined lambda parameters

### ISSUE THREAD

**Issue by He1pa** [kcl-lang/kcl#870]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

![image](https://github.com/kcl-lang/kcl/assets/56333845/9abdbf77-c99b-4681-87cc-e9fd45dc4007)

### 2. What did you expect to see? (Required)
the error should be under `Person`

**Comment by Peefy** [comment]
Closed by #873
