### ISSUE TITLE
Pure Rust SDK/crate?

### ISSUE THREAD

**Issue by patrycju** [kcl-lang/kcl#931]
## Pure Rust SDK crate?

Hi!

I'm considering KCL for my project, and I'm wondering if you provide pure Rust SDK crate. It doesn't seem like it, as KCLVM crates build straight to cdylib or LLVM/C interface.

How can I integrate KCL into my Rust codebase? Is it possible to omit LLVM entirely? Are there any public KCL crates published or do I need to have both repos on disk and reference KCL by path somehow?

Thanks!

**Comment by Peefy** [comment]
Hi @patrycju. We are sorry that we currently do not have a pure Rust SDK now, but we have provided a pure Go/Python SDK based on cdylib, which is very easy to use. I think we will provide the pure Rust SDK version v0.7.0 on crates.io as soon as next week (without LLVM dependency). 

In addition, thank you for your attention to the KCL project. I would like to inquire about the APIs and scenarios where you use KCL in the Rust codebase.

**Comment by patrycju** [comment]
It's hard not to give attention to such a great tool, well done 👏 I actually believe that KCL will replace YAML, Helm, Kustomize etc as a preferred configuration language. As a DevOps, I'm so excited for first class support for Kubernetes objects (standard and CRDs) and ability to create models/schemas from OpenAPI specs, it's going to save me so much work!

Anyway, as for my project, I can't really say for sure because none of the integration is implemented yet, but I want to:
- Be able to eval KCL programs/configuration files and load parsed objects into structs
- Validate configuration files against schema/rules
- Export loaded structs to KCL files, or JSON/YAML
- Parse multiple KCL files at once, e.g. in single directory or all sub-directories, respecting import statements found in KCLs

Not sure if that helped in any way, but there you go 😄

**Comment by Peefy** [comment]
We have release a alpha version for KCL pure KCL SDK here: https://github.com/kcl-lang/lib
