### ISSUE TITLE
Refactor: remove internal schema settings plan.

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl#94]
## Introduction

KCL provides the schema settings meta attribute for planning YAML. In addition, you can also write KCL code to customize the way of outputting YAML, so the settings meta attribute function can be removed, reducing the burden of understanding.

## Background

* At present, the YAML output of kcl is hardcode in KCLVM, and some variables will be undefined and filtered according to the schema's __settings__: {"output_type": } to control the output to stdout or file, and all yaml will be generated in the same one In the file, different YAML uses --- to split
* In order to control the order or pattern of YAML output, users need to understand the YAML output logic in KCLVM and write a lot of KCL code, such as modifying the __settings__ of the schema or controlling the instantiation order of resources, it is better to directly get all the resources for processing, such as Sorting and outputting is intuitive, and the type of the subsequent schema output_type can not be written, and the output to stdout and files can be controlled at the same time by writing code, and it can be output directly inside the schema, etc., flexible use
* On the other hand, after customizing the output YAML, the Konfig front-end can be freely written, in line with user best practices and the needs of upper-level operation and maintenance automation, the corresponding output module can be adjusted according to the needs
* For example, in the current large library, OutputMixin is used to control the output style of all k8s resources. It can be seen that the code is more complex and needs to be used as a mixin. It is better to output directly in the back-end model render.

## Design

```
schema ManifestsYamlStreamOptions:
    sort_keys: bool = False
    ignore_private: bool = True
    ignore_none: bool = False
    separator: str = "\n---\n"

manifests.yaml_stream(values: [any], * , opts: ManifestsYamlStreamOptions = ManifestsYamlStreamOptions {})
```

The function is to serialize a list of KCL objects to YAML and output using the style with the `---` delimiter, and add it to the existing YAML output stream.

> Note: When the yaml.manifest_stream function is called, the output result of plan inside KCLVM is subject to this function, and global variables are not output by default.

## Examples

```kcl
import manifests

# resources.k
schema Deployment:
    apiVersion: str = "v1"
    kind: str = "Deployment"
    metadata: {str:} = {
        name = "deploy"
    }
    spec: {str:} = {
        replica = 2
    }

schema Service:
    apiVersion: str = "v1"
    kind: str = "Service"
    metadata: {str:} = {
         name = "svc"
    }
    spec: {str:} = {}    
        
deployments = [Deployment {}, Deployment {}]
services = [Service {}, Service {}]

manifests.yaml_stream(deployments + services)
```

The output YAML is

```yaml
apiVersion: v1
kind: Deployment
metadata:
  name: deploy
spec:
  replica: 2
---
apiVersion: v1
kind: Deployment
metadata:
  name: deploy
spec:
  replica: 2
---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec: {}
--
apiVersion: v1
kind: Service
metadata:
  name: svc
spec: {}
```

## Reference

* Ksonnet: https://github.com/ksonnet/ksonnet
* Jsonnet Manifest Functions: https://jsonnet.org/ref/stdlib.html (using std.)

```jsonnet
std.manifestYamlStream(
  ['a', 1, []],
  indent_array_in_object=false,
  c_document_end=true)
{
    a: 1,
    b: 2
}
```

The output is

```
"---\n\"a\"\n---\n1\n---\n[]\n...\n{\"a\": 1, \"b\": 2}"
```

* CUE Kubernetes Integration: https://cuelang.org/docs/integrations/k8s/  (using yaml.MarshalStream(objects))

```cue
package kube

objects: [ for v in objectSets for x in v {x}]

objectSets: [
	service,
	deployment,
	statefulSet,
	daemonSet,
	configMap,
]
```

```
package kube

import (
	"encoding/yaml"
	"tool/cli"
)

command: dump: {
	task: print: cli.Print & {
		text: yaml.MarshalStream(objects)
	}
}
```

## Note

schema `__settingss__` attrtibute will be removed in KCLVM v0.4.6

**Comment by Peefy** [comment]
包名
* yaml -> manifest

**Comment by chai2010** [comment]
输出的行为应该和语言保持独立，如何混合在一起会带来一些额外的噪声。
如果是高级的用户需要定制行为，是否可以通过API或语法之外的配套能力提供。

**Comment by Peefy** [comment]
> 

I agree with this suggestion. For example, for the Kusion Engine YAML Manifest format, we can write the corresponding KCL code to assemble this configuration, which can be generated by middle-tier tools or APIs, while KCL can retain a default YAML planning output style, but the middle layer needs a way to specify the KCL configuration that needs to be output, like `objects` in the cue code mentioned in the issue.

**Comment by Peefy** [comment]
> 输出的行为应该和语言保持独立，如何混合在一起会带来一些额外的噪声。 如果是高级的用户需要定制行为，是否可以通过API或语法之外的配套能力提供。

Just like jsonnet used in kube-prometheus, they use a gojsontoyaml tool to generate YAML manifests https://github.com/prometheus-operator/kube-prometheus/blob/main/build.sh#L18
