### ISSUE TITLE
KCL test return {"code":-32601,"message":"Method not found"}

### ISSUE THREAD

**Issue by remy2wescale** [kcl-lang/kcl#951]
### 1. Minimal reproduce step

Example taken from KCL documentation : https://kcl-lang.io/docs/tools/cli/kcl/test
#### hello.k
```hcl
schema Person:
    name: str = "kcl"
    age: int = 1

hello = Person {
    name = "hello kcl"
    age = 102
}
```

#### hello_test.k

```hcl
test_person = lambda {
    a = Person{}
    assert a.name == 'kcl'
}
test_person_age = lambda {
    a = Person{}
    assert a.age == 1
}
test_person_ok = lambda {
    a = Person{}
    assert a.name == "kcl"
    assert a.age == 1
}
```

### 2. What did you expect to see? 

```
$ kcl test
test_person: PASS (2ms)
test_person_age: PASS (1ms)
test_person_ok: PASS (1ms)
--------------------------------------------------------------------------------
PASS: 3/3
```
### 3. What did you see instead 
```
$ ls
hello.k  hello_test.k
$ kcl test
Error: {"code":-32601,"message":"Method not found"}
```
### 4. What is your KCL components version? 
0.7.0-linux-amd64

**Comment by Peefy** [comment]
@remy2wescale Hi there. Sorry for the late reply. I can't reproduce this issue. Could you please tell me how you installed KCL and what are the outputs of the following two commands?

```shell
which kcl
```

```shell
which kclvm_cli
```

**Comment by remy2wescale** [comment]
Hello Peey, no problem, with your message, i've been able to find a solution.
And yes, the problem seems to stem from an older version that was in PATH.
Just for information, i have upgraded KCL from 0.5.5 to 0.7 with the installer script from the documentation (
`wget -q https://kcl-lang.io/script/install-kcl-lsp.sh -O - | /bin/bash`)
```
$ which kcl
/usr/local//bin/kcl
```
```
$ which kclvm_cli
/usr/local/kclvm/bin/kclvm_cli
```
```
$ kclvm_cli version
Version: 0.5.5-20ab3eb4b9179219d6837a57f5d35286
Platform: x86_64-unknown-linux-gnu
GitCommit: VERGEN_IDEMPOTENT_OUTPUT
```

Remove `export PATH="/usr/local/kclvm/bin:$PATH"` line in `~/.bashrc` :

```
$ kclvm_cli version
Version: 0.7.0-20ab3eb4b9179219d6837a57f5d35286
Platform: x86_64-unknown-linux-gnu
GitCommit: VERGEN_IDEMPOTENT_OUTPUT
```

```
$ kcl test
test_person: PASS (0ms)
test_person_age: PASS (0ms)
test_person_ok: PASS (1ms)
--------------------------------------------------------------------------------
PASS: 3/3
```

:tada: 

Thank you for your help :+1:
