### ISSUE TITLE
[LFX] LSP quick fix for kcl compiler

### ISSUE THREAD

**Issue by He1pa** [kcl-lang/kcl#997]
Provide quick fix capability with LSP for kcl compiler
![image](https://github.com/kcl-lang/kcl/assets/56333845/e0619a76-27a4-4033-adc3-2ac9e5a62590)

## How to apply
1. Submit an application on the LFX membership platform.
2. Complete the pretest
3. Wait for the result

## Pretest 
To apply for this mentorship, you **MUST** finish a pre-test. Pre-test link: https://github.com/kcl-lang/kcl/issues/1020

## Detail
    + According to different errors, provide different quick_fix schemes in the KCL compiler,
That is, provide `suggested_replacement` in the structure below. Now, this field is almost entirely `None`

```
pub struct Message {
    pub range: Range,
    pub style: Style,
    pub message: String,
    pub note: Option<String>,
    pub suggested_replacement: Option<String>,
}
```

This field will be processed as a CodeAction response in the LSP, and provide quick fix capability in editor.

## Appendix
LSP Overview:  
+ https://code.visualstudio.com/api/language-extensions/overview
+ https://code.visualstudio.com/api/language-extensions/language-server-extension-guide

LSP spec: 
+ https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_codeAction

quick fix impl pr:
+  https://github.com/kcl-lang/kcl/pull/652

**Comment by Ishani217** [comment]
Hey @He1pa 
I would like to work on this issue under the LFX Mentorship Program.
Since the LFX Mentorship is not started yet, and is under project proposal period, I would like to break down this issue and start creating some child issues to QuickStart the work
//cc @zong-zhe

**Comment by He1pa** [comment]
> Hi! I would like to work on this issue under the upcoming LFX term. Are there ant related issues to the same, which I can parse through or try to solve as pre-tasks for the same?

Sorry, I didn't understand what you meant 'Are there ant related issues to the same'?
But if you are interested in this, you can take a look at the previous PR first:  https://github.com/kcl-lang/kcl/pull/652

**Comment by EshaanAgg** [comment]
Hi @He1pa! Thanks for the detailed response. Since this is an LFX issue, I thought the same would be frozen for contributors until the mentees are officially announced, and thus, I asked for any other related child issues, sort of qualifying tasks for the term.

**Comment by He1pa** [comment]
> Hi @He1pa! Thanks for the detailed response. Since this is an LFX issue, I thought the same would be frozen for contributors until the mentees are officially announced, and thus, I asked for any other related child issues, sort of qualifying tasks for the term.

Do you want me to provide a pretest to determine candidates? I will provide a new issue as soon as possible, this issue is to solve a smaller but related problem

**Comment by 7h3-3mp7y-m4n** [comment]
hey @He1pa , I would like to work on this

**Comment by literalEval** [comment]
> > Hi @He1pa! Thanks for the detailed response. Since this is an LFX issue, I thought the same would be frozen for contributors until the mentees are officially announced, and thus, I asked for any other related child issues, sort of qualifying tasks for the term.
> 
> Do you want me to provide a pretest to determine candidates? I will provide a new issue as soon as possible, this issue is to solve a smaller but related problem

Hey @He1pa it would be great if you can provide some pretests :)

I have prior experience in building custom linters and custom fixes for errors. Please look at this [issue](https://github.com/PalisadoesFoundation/talawa/issues/1479) where I created a documentation checking linter from scratch for the Dart/Flutter codebase.

Excited to work on this project.

**Comment by Peefy** [comment]
Dup with #1125
